import {useEffect,useState} from 'react';
import {ShieldCheck,LogOut,RefreshCw} from 'lucide-react';
import {api,ApiError,faDateTime} from './api';
import {useLocale,translate as t} from './i18n';
import {w} from './copy';
type Session={id:string;current:boolean;lastSeen:string;expiresAt:string};
export function AccountSecurity({onExpired}:{onExpired:()=>void}){
 useLocale();const[sessions,setSessions]=useState<Session[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirm,setConfirm]=useState(false);
 async function load(){try{setSessions((await api<{sessions:Session[]}>('/auth/sessions')).sessions);}catch(e){setError((e as Error).message);if(e instanceof ApiError&&e.status===401)onExpired();}}
 useEffect(()=>{load();},[]);
 async function revoke(id?:string){setBusy(true);setError('');try{if(id){const r=await api<{current:boolean}>('/auth/sessions/'+id,'DELETE');if(r.current){onExpired();return;}}else await api('/auth/revoke-others','POST',{});setConfirm(false);await load();setNotice(w('نشست‌های انتخاب‌شده باطل شدند.','Selected sessions have been revoked.','تم إبطال الجلسات المحددة.','Seçilen oturumlar iptal edildi.'));}catch(e){setError((e as Error).message);if(e instanceof ApiError&&e.status===401)onExpired();}finally{setBusy(false);}}
 return <section className="ops-panel"><div className="ops-panel-title"><div><span className="section-kicker">{w('امنیت حساب شخصی','PERSONAL ACCOUNT SECURITY','أمان الحساب الشخصي','KİŞİSEL HESAP GÜVENLİĞİ')}</span><h2><ShieldCheck size={20}/>{w('نشست‌های فعال من','My active sessions','جلساتي النشطة','Etkin oturumlarım')}</h2></div><button className="secondary" disabled={busy} onClick={load}><RefreshCw size={16}/>{t('به‌روزرسانی')}</button></div><p className="panel-explainer">{w('فقط نشست‌های حساب خودتان نمایش داده می‌شوند. با ابطال نشست، ادامه کار در آن مرورگر به ورود دوباره نیاز دارد. هیچ رمز یا توکن ورود نمایش داده نمی‌شود.','Only your own account sessions are shown. Revoking a session requires that browser to sign in again. No password or login token is displayed.','تُعرض جلسات حسابك فقط. يتطلب إبطال الجلسة تسجيل الدخول مجدداً في ذلك المتصفح. لا تظهر كلمات مرور أو رموز دخول.','Yalnızca kendi hesabınızın oturumları gösterilir. İptal edilen oturumun tarayıcısı yeniden giriş yapmalıdır. Parola veya giriş belirteci gösterilmez.')}</p>{error&&<div className="notice error" role="alert">{t(error)}</div>}{notice&&<p className="notice success" role="status">{notice}</p>}<div className="table-scroll"><table><thead><tr><th>{w('نشست','Session','الجلسة','Oturum')}</th><th>{w('آخرین فعالیت','Last activity','آخر نشاط','Son etkinlik')}</th><th>{w('پایان اعتبار','Expires','انتهاء الصلاحية','Sona erme')}</th><th>{t('اقدام')}</th></tr></thead><tbody>{sessions.map((s,i)=><tr key={s.id}><td>{s.current?w('مرورگر فعلی','Current browser','المتصفح الحالي','Mevcut tarayıcı'):w('مرورگر دیگر','Another browser','متصفح آخر','Başka tarayıcı')+' '+(i+1)}</td><td>{faDateTime(s.lastSeen)}</td><td>{faDateTime(s.expiresAt)}</td><td><button className="secondary" disabled={busy} onClick={()=>revoke(s.id)}><LogOut size={16}/>{w('خروج این نشست','Sign out this session','تسجيل خروج هذه الجلسة','Bu oturumu kapat')}</button></td></tr>)}</tbody></table></div>{!confirm?<button className="secondary" disabled={busy||sessions.filter(s=>!s.current).length===0} onClick={()=>setConfirm(true)}>{w('خروج همه مرورگرهای دیگر','Sign out all other browsers','تسجيل خروج كل المتصفحات الأخرى','Diğer tüm tarayıcıları kapat')}</button>:<div className="notice amber"><p>{w('تمام نشست‌های دیگر باطل می‌شوند؛ نشست فعلی باقی می‌ماند.','All other sessions will be revoked; this session remains active.','سيتم إبطال كل الجلسات الأخرى؛ تبقى الجلسة الحالية نشطة.','Diğer tüm oturumlar iptal edilir; mevcut oturum etkin kalır.')}</p><button className="primary" disabled={busy} onClick={()=>revoke()}>{w('تأیید خروج نشست‌ها','Confirm session revocation','تأكيد إبطال الجلسات','Oturum iptalini onayla')}</button><button className="secondary" disabled={busy} onClick={()=>setConfirm(false)}>{t('انصراف')}</button></div>}</section>;
}
