import {useState} from 'react';
import {TrendingUp,SlidersHorizontal,Download} from 'lucide-react';
import {calculateEconomics,type EconomicsInput} from './economics';
import {faNumber} from './api';
import {useLocale,translate as t} from './i18n';
const initial:EconomicsInput={quantity:4000000,scrapBefore:5,scrapAfter:3.8,rejectNetCost:12000,downtimeHours:100,downtimeReduction:20,avoidableHourlyLoss:2000000,energyCost:400000000,energyReduction:6,releasedHours:400,hourValue:200000,cashLabor:false,investment:1000000000,annualOperatingCost:180000000,realization:100};
const fields:{key:keyof EconomicsInput;label:string;unit:string;percent?:boolean;hint:string}[]=[{key:'quantity',label:'تولید سالانه',unit:'قطعه',hint:'تعداد تولید همان خانواده محصول و بازه'},{key:'scrapBefore',label:'ضایعات خط مبنا',unit:'درصد',percent:true,hint:'از تعداد معیوب تأییدشده، قبل از اجرای طرح'},{key:'scrapAfter',label:'ضایعات هدف',unit:'درصد',percent:true,hint:'سناریو یا نتیجه اندازه‌گیری‌شده بعد از پایلوت'},{key:'rejectNetCost',label:'زیان خالص هر قطعه معیوب',unit:'تومان',hint:'مواد و فرآوری قابل اجتناب منهای بازیافت؛ قیمت فروش نیست'},{key:'downtimeHours',label:'توقف قابل بهبود سالانه',unit:'ساعت',hint:'توقف غیر برنامه‌ریزی‌شده مرتبط با طرح'},{key:'downtimeReduction',label:'کاهش توقف هدف',unit:'درصد',percent:true,hint:'با رخدادنامه و خط مبنا صحه‌گذاری شود'},{key:'avoidableHourlyLoss',label:'زیان قابل اجتناب هر ساعت توقف',unit:'تومان',hint:'حاشیه مشارکت از دست رفته؛ هزینه ثابت را دوباره نشمارید'},{key:'energyCost',label:'هزینه انرژی سالانه',unit:'تومان',hint:'صورتحساب هم‌بازه و هم‌دامنه با تولید'},{key:'energyReduction',label:'کاهش هزینه انرژی هدف',unit:'درصد',percent:true,hint:'پس از تعدیل حجم و ترکیب محصول'},{key:'releasedHours',label:'ساعت کنترل کیفیت آزادشده',unit:'ساعت',hint:'ارزش بهره‌وری؛ خودبه‌خود صرفه‌جویی نقدی نیست'},{key:'hourValue',label:'ارزش هر ساعت آزادشده',unit:'تومان',hint:'هزینه یا ارزش فرصت تأییدشده سازمان'},{key:'investment',label:'سرمایه‌گذاری کل پروژه',unit:'تومان',hint:'تمام مراحل و تجهیزات، از جمله اعتبار قبلی'},{key:'annualOperatingCost',label:'هزینه بهره‌برداری سالانه',unit:'تومان',hint:'سرور، پشتیبانی، کالیبراسیون و اجاره مداوم'}];
export function BenefitCalculator(){
 useLocale();const[v,setV]=useState(initial);let result:ReturnType<typeof calculateEconomics>|null=null,error='';try{result=calculateEconomics(v);}catch(e){error=(e as Error).message;}
 const save=()=>{const rows=[[t('سناریوی اقتصادی'),t('برآورد بر اساس مفروضات')],...Object.entries(v),...Object.entries(result||{})];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(row=>row.join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='fanarlool-economic-scenario.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section className="benefit-workbench"><div className="panel"><div className="panel-title"><h2><TrendingUp size={21}/> {t('سنجش ارزش اقتصادی طرح')}</h2><button className="secondary" onClick={save} disabled={!result}><Download size={16}/> {t('خروجی سناریو')}</button></div><p className="section-caption">{t('اعداد اولیه یک مثال قابل تغییرند. مبنا را از اسناد کارخانه وارد کنید؛ نتیجه، برآورد همان مفروضات است و تعهد صرفه‌جویی محسوب نمی‌شود.')}</p><div className="economics-form">{fields.map(f=><label key={f.key}>{t(f.label)}<span>{t(f.unit)}</span><input type="number" min={0} max={f.percent?100:undefined} step="any" value={Number(v[f.key])} onChange={e=>setV({...v,[f.key]:Number(e.target.value)})}/><small>{t(f.hint)}</small></label>)}</div><label className="cash-labor-toggle"><input type="checkbox" checked={v.cashLabor} onChange={e=>setV({...v,cashLabor:e.target.checked})}/>{t('ارزش نیروی آزادشده واقعاً هزینه نقدی قابل اجتناب است و در ROI منظور شود.')}</label><div className="sensitivity-control"><SlidersHorizontal size={19}/><label>{t('تحقق مفروضات')} <b>{faNumber(v.realization)}%</b><input aria-label={t('درصد تحقق سناریو')} type="range" min={0} max={100} step={5} value={v.realization} onChange={e=>setV({...v,realization:Number(e.target.value)})}/></label></div>{error&&<div className="notice error">{t(error)}</div>}</div>{result&&<><div className="metric-grid">{[
 [t('منفعت نقدی ناخالص سالانه'),faNumber(result.gross/1000000,1)+' '+t('میلیون تومان'),t('پس از ضریب تحقق')],
 [t('منفعت خالص سالانه'),faNumber(result.net/1000000,1)+' '+t('میلیون تومان'),t('پس از هزینه بهره‌برداری')],
 [t('بازگشت ساده سرمایه'),result.paybackMonths===null?t('فاقد بازگشت مثبت'):faNumber(result.paybackMonths,1)+' '+t('ماه'),t('سرمایه‌گذاری ÷ منفعت خالص')],
 [t('قطعه معیوب قابل اجتناب'),faNumber(result.avoidedDefects),t('با فرض رسیدن به نرخ هدف')]
 ].map(r=><article className="metric-card" key={r[0]}><span>{r[0]}</span><strong className="economic-number">{r[1]}</strong><small>{r[2]}</small></article>)}</div><div className="panel"><h2>{t('اجزای منفعت و شیوه اثبات')}</h2><div className="saving-bars">{[
 ['کاهش ضایعات',result.scrap,'تولید × اختلاف نرخ × زیان خالص قطعه'],['کاهش توقف',result.downtime,'ساعت توقف × درصد کاهش × زیان هر ساعت'],['بهبود انرژی',result.energy,'هزینه انرژی × درصد کاهش'],['ارزش فرصت نیروی انسانی',result.opportunity,v.cashLabor?'در جریان نقدی منظور شده':'جدا از جریان نقدی']
 ].map(([label,value,formula])=><div key={String(label)}><span>{t(label)}<small>{t(formula)}</small></span><b>{faNumber(Number(value)/1000000,1)} {t('میلیون تومان')}</b></div>)}</div><p className="section-caption">{t('برای ارائه به ناظر: خط مبنا، بازه، خانواده قطعه، سند هزینه، تغییر mix محصول و ساعات واقعی را پیوست کنید. روش بازگشت ساده، ارزش زمانی پول، مالیات و جریان نقد ماهانه را لحاظ نمی‌کند.')}</p></div></>}</section>;
}
