import {useEffect,useRef,useState} from 'react';
import {Camera,Download,Square} from 'lucide-react';
import {useLocale} from './i18n';
import {faNumber} from './api';

const labels={
 fa:{title:'آزمایش دوربین محلی',intro:'تصویر زنده از دوربین دستگاه شما؛ برای بررسی زاویه، نور و کادر پیش از طراحی بازرسی صنعتی.',privacy:'تصویر در همین مرورگر پردازش می‌شود. عکس فقط روی دستگاه شما دانلود می‌شود و به سرور ارسال نمی‌شود. این ابزار تشخیص عیب هوش مصنوعی یا اندازه‌گیری کالیبره‌شده انجام نمی‌دهد.',start:'فعال‌کردن دوربین',starting:'در حال درخواست دسترسی…',stop:'توقف دوربین',download:'دانلود عکس PNG',dimensions:'ابعاد واقعی فریم',waiting:'برای مشاهده تصویر، دسترسی دوربین را فعال کنید.',denied:'اجازه دوربین داده نشد. مجوز دوربین این سایت را در تنظیمات مرورگر بررسی کنید.',missing:'دوربین قابل دسترس پیدا نشد.',busy:'دوربین در دسترس نیست یا برنامه دیگری از آن استفاده می‌کند.',unsupported:'مرورگر یا اتصال فعلی از دسترسی امن دوربین پشتیبانی نمی‌کند.',failed:'دوربین فعال نشد؛ اتصال دستگاه و مجوز مرورگر را بررسی کنید.',saveFailed:'عکس ذخیره نشد. پس از نمایش فریم دوباره تلاش کنید.',pixel:'پیکسل',ended:'دسترسی دوربین پایان یافت؛ می‌توانید دوباره آن را فعال کنید.'},
 en:{title:'Local camera workbench',intro:'Live video from your device camera to review angle, lighting and framing before industrial inspection design.',privacy:'Video stays in this browser. Snapshots download only to your device and are not uploaded. This tool does not perform AI defect detection or calibrated measurement.',start:'Enable camera',starting:'Requesting permission…',stop:'Stop camera',download:'Download PNG snapshot',dimensions:'Actual frame dimensions',waiting:'Enable camera access to see live video.',denied:'Camera permission was denied. Check this site’s camera permission in your browser settings.',missing:'No accessible camera was found.',busy:'The camera is unavailable or is being used by another application.',unsupported:'This browser or connection does not support secure camera access.',failed:'The camera could not start; check the device connection and browser permission.',saveFailed:'Snapshot could not be saved. Try again after a frame appears.',pixel:'pixels',ended:'Camera access ended; you can enable it again.'},
 ar:{title:'اختبار الكاميرا المحلية',intro:'فيديو مباشر من كاميرا جهازك لمراجعة الزاوية والإضاءة والإطار قبل تصميم الفحص الصناعي.',privacy:'يبقى الفيديو في هذا المتصفح. تُنزّل الصور على جهازك فقط ولا تُرفع إلى الخادم. لا تنفذ هذه الأداة كشف العيوب بالذكاء الاصطناعي أو القياس المعاير.',start:'تفعيل الكاميرا',starting:'جارٍ طلب الإذن…',stop:'إيقاف الكاميرا',download:'تنزيل صورة PNG',dimensions:'أبعاد الإطار الفعلية',waiting:'فعّل إذن الكاميرا لعرض الفيديو المباشر.',denied:'لم يُمنح إذن الكاميرا. تحقق من إذن هذا الموقع في إعدادات المتصفح.',missing:'لم يتم العثور على كاميرا متاحة.',busy:'الكاميرا غير متاحة أو يستخدمها تطبيق آخر.',unsupported:'لا يدعم المتصفح أو الاتصال الحالي الوصول الآمن إلى الكاميرا.',failed:'تعذر تشغيل الكاميرا؛ تحقق من اتصال الجهاز وإذن المتصفح.',saveFailed:'تعذر حفظ الصورة. حاول مجدداً بعد ظهور إطار.',pixel:'بكسل',ended:'انتهى الوصول إلى الكاميرا؛ يمكنك تفعيلها مجدداً.'},
 tr:{title:'Yerel kamera çalışma alanı',intro:'Endüstriyel kontrol tasarımı öncesinde açı, aydınlatma ve kadrajı incelemek için cihaz kameranızdan canlı görüntü.',privacy:'Görüntü bu tarayıcıda kalır. Fotoğraflar yalnız cihazınıza indirilir ve sunucuya yüklenmez. Bu araç yapay zekâ ile kusur tespiti veya kalibre ölçüm yapmaz.',start:'Kamerayı etkinleştir',starting:'İzin isteniyor…',stop:'Kamerayı durdur',download:'PNG fotoğraf indir',dimensions:'Gerçek kare boyutları',waiting:'Canlı görüntü için kamera erişimini etkinleştirin.',denied:'Kamera izni verilmedi. Tarayıcı ayarlarında bu sitenin kamera iznini kontrol edin.',missing:'Erişilebilir kamera bulunamadı.',busy:'Kamera kullanılamıyor veya başka bir uygulama tarafından kullanılıyor.',unsupported:'Bu tarayıcı veya bağlantı güvenli kamera erişimini desteklemiyor.',failed:'Kamera başlatılamadı; cihaz bağlantısını ve tarayıcı iznini kontrol edin.',saveFailed:'Fotoğraf kaydedilemedi. Görüntü geldikten sonra tekrar deneyin.',pixel:'piksel',ended:'Kamera erişimi sona erdi; yeniden etkinleştirebilirsiniz.'}
};
type ErrorKey='denied'|'missing'|'busy'|'unsupported'|'failed'|'saveFailed'|'ended';

export default function CameraWorkbench(){
 const {locale}=useLocale(),c=labels[locale];
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),generation=useRef(0),mounted=useRef(true),urls=useRef(new Set<string>());
 const [active,setActive]=useState(false),[pending,setPending]=useState(false),[size,setSize]=useState({width:0,height:0}),[error,setError]=useState<ErrorKey|null>(null);
 const release=()=>{const current=stream.current;stream.current=null;current?.getTracks().forEach(track=>{track.onended=null;track.stop();});if(video.current)video.current.srcObject=null;};
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;generation.current++;release();urls.current.forEach(url=>URL.revokeObjectURL(url));urls.current.clear();};},[]);
 const stop=()=>{generation.current++;release();setActive(false);setPending(false);setSize({width:0,height:0});setError(null);};
 const start=async()=>{
  if(pending||active)return;const token=++generation.current;setError(null);
  if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){setError('unsupported');return;}
  setPending(true);
  try{
   const incoming=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});
   if(!mounted.current||token!==generation.current){incoming.getTracks().forEach(track=>track.stop());return;}
   stream.current=incoming;
   incoming.getVideoTracks().forEach(track=>{track.onended=()=>{if(!mounted.current||stream.current!==incoming)return;generation.current++;release();setActive(false);setPending(false);setSize({width:0,height:0});setError('ended');};});
   const element=video.current;if(!element)throw new Error('Video element unavailable');element.srcObject=incoming;await element.play();
   if(!mounted.current||token!==generation.current)return;setActive(true);
  }catch(reason){
   if(!mounted.current||token!==generation.current)return;release();setActive(false);setSize({width:0,height:0});
   const name=reason instanceof DOMException?reason.name:'';setError(name==='NotAllowedError'||name==='SecurityError'?'denied':name==='NotFoundError'||name==='DevicesNotFoundError'?'missing':name==='NotReadableError'||name==='TrackStartError'?'busy':'failed');
  }finally{if(mounted.current&&token===generation.current)setPending(false);}
 };
 const capture=()=>{
  const element=video.current;if(!active||!element||element.readyState<2||!element.videoWidth||!element.videoHeight){setError('saveFailed');return;}
  const token=generation.current,canvas=document.createElement('canvas');canvas.width=element.videoWidth;canvas.height=element.videoHeight;
  try{const context=canvas.getContext('2d');if(!context)throw new Error('Canvas unavailable');context.drawImage(element,0,0);canvas.toBlob(blob=>{if(!mounted.current||token!==generation.current)return;if(!blob){setError('saveFailed');return;}const url=URL.createObjectURL(blob);urls.current.add(url);const link=document.createElement('a');link.href=url;link.download='fanarlool-camera-'+new Intl.DateTimeFormat('en-u-ca-persian',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'Asia/Tehran'}).format(new Date()).replace(/\//g,'-')+'.png';link.click();setTimeout(()=>{URL.revokeObjectURL(url);urls.current.delete(url);},1000);setError(null);},'image/png');}catch{setError('saveFailed');}
 };
 const updateSize=()=>{const element=video.current;if(element)setSize({width:element.videoWidth,height:element.videoHeight});};
 return <section className="panel camera-workbench"><div className="panel-title"><h2><Camera size={22}/> {c.title}</h2></div><p>{c.intro}</p><div className="notice subtle">{c.privacy}</div><div style={{display:'flex',gap:12,flexWrap:'wrap',marginBlock:'16px'}}><button type="button" className="primary" disabled={active||pending} onClick={start}><Camera size={18}/>{pending?c.starting:c.start}</button><button type="button" className="secondary" disabled={!active&&!pending} onClick={stop}><Square size={18}/>{c.stop}</button><button type="button" className="secondary" disabled={!active||!size.width} onClick={capture}><Download size={18}/>{c.download}</button></div>{error&&<p className="notice error" role="alert">{c[error]}</p>}<video ref={video} muted playsInline autoPlay onLoadedMetadata={updateSize} onResize={updateSize} aria-label={c.title} style={{width:'100%',maxHeight:560,background:'#102735',borderRadius:12,objectFit:'contain',display:active||pending?'block':'none'}}/>{!active&&!pending&&<p className="section-caption">{c.waiting}</p>}{size.width>0&&<p role="status">{c.dimensions}: <b dir="ltr">{faNumber(size.width)} × {faNumber(size.height)}</b> {c.pixel}</p>}</section>;
}
