import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ClipboardCheck,Search,X} from 'lucide-react';
import {translate as t,useLocale} from './i18n';
import {w} from './copy';
import {faNumber,statusLabels,type Workspace,type RecordRow} from './api';
import {recordTitle} from './operationsInsights';
export function CommandSearch({workspace,onRecord,onClose}:{workspace:Workspace;onRecord:(row:RecordRow)=>void;onClose:()=>void}){
 useLocale();const[query,setQuery]=useState('');const dialog=useRef<HTMLElement>(null),input=useRef<HTMLInputElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement|null;input.current?.focus();const handle=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button,input')||[]);if(!nodes.length)return;if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes[nodes.length-1].focus();}else if(!e.shiftKey&&document.activeElement===nodes[nodes.length-1]){e.preventDefault();nodes[0].focus();}}};document.addEventListener('keydown',handle);return()=>{document.removeEventListener('keydown',handle);previous?.focus();};},[onClose]);
 const rows=workspace.records.filter(r=>!query||[r.id,r.creator_name,...Object.values(r.data)].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase())).slice(0,20);
 return <div className="command-backdrop"><section ref={dialog} className="command-dialog" role="dialog" aria-modal="true" aria-labelledby="command-title"><header><h2 id="command-title">{w('جست‌وجوی پرونده‌های کارخانه','Search factory records','البحث في سجلات المصنع','Fabrika kayıtlarında ara')}</h2><button className="icon-button" onClick={onClose} aria-label={t('بستن')}><X size={20}/></button></header><label className="command-input"><Search size={20}/><input ref={input} aria-label={w('جست‌وجوی سراسری','Global search','البحث الشامل','Genel arama')} placeholder={w('بچ، قطعه، تجهیز، ابزار یا مسئول…','Batch, part, asset, instrument or owner…','الدفعة أو القطعة أو المعدات أو الأداة أو المسؤول…','Parti, parça, varlık, cihaz veya sorumlu…')} value={query} onChange={e=>setQuery(e.target.value)}/><kbd>ESC</kbd></label><p>{w('جست‌وجو فقط در سوابقی است که نقش شما اجازه مشاهده دارد.','Search covers only records your role may view.','يشمل البحث السجلات التي يسمح دورك بعرضها فقط.','Arama yalnızca rolünüzün görebildiği kayıtları kapsar.')}</p><div className="command-results">{rows.map(r=><button key={r.id} onClick={()=>{onRecord(r);onClose();}}><ClipboardCheck size={19}/><span><strong>{recordTitle(r)}</strong><small>{t(workspace.catalog.find(c=>c.kind===r.kind)?.title)} · {r.creator_name}</small></span><span className={`badge ${r.status}`}>{t(statusLabels[r.status])}</span><ArrowLeft size={15}/></button>)}</div>{!rows.length&&<p>{w('پرونده‌ای مطابق جست‌وجو یافت نشد.','No record matches this search.','لم يعثر على سجل مطابق للبحث.','Aramayla eşleşen kayıt bulunamadı.')}</p>}<footer>{faNumber(rows.length)} {w('نتیجه؛ حداکثر ۲۰ مورد','results; up to 20','نتيجة؛ حتى 20','sonuç; en fazla 20')}</footer></section></div>;
}
