import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Layers,RefreshCw,Save,Search,Download,GitCompareArrows,History,SlidersHorizontal} from 'lucide-react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend} from 'recharts';
import {api,faNumber,faDateTime,type User,type Workspace} from './api';
import {w} from './copy';
import {useLocale} from './i18n';
import {csvCell} from './csv';
import {depthError} from './productDepthCopy';
import './product-depth.css';
type Inputs={wireDiameter:number;meanDiameter:number;freeLength:number;activeCoils:number;totalCoils:number;force:number;shearModulus:number;allowableStress:number};
type Outputs={rate:number;stress:number;deflection:number;length:number;solidHeight:number;availableDeflection:number;solidForce:number;clearance:number;index:number;wahl:number;safetyFactor:number|null;validLinear:boolean;warnings:string[]};
type Preview={inputs:Inputs;outputs:Outputs;baseline:{inputs:Inputs;outputs:Outputs};reference:{assetCode:string;assetName:string;recipePart:string;recipeRevision:string;recipeMaterial:string;recipeVersion:number;assetVersion:number};loadCurve:{force:number;baselineDeflection:number;candidateDeflection:number;baselineValidLinear:boolean;candidateValidLinear:boolean}[];model?:{id:string}};
type Scenario=Preview&{id:string;title:string;assetId:string;recipeId:string;ownerId:string;ownerName:string;version:number;reason:string;createdAt:string;updatedAt:string};
type Snapshot={scenarios:Scenario[];total:number;page:number;pageSize:number;permissions:{read:boolean;write:boolean};model:{id:string};generatedAt:string;source:string};
const defaults:Inputs={wireDiameter:12,meanDiameter:110,freeLength:320,activeCoils:6,totalCoils:8,force:3000,shearModulus:78500,allowableStress:880};
const names=()=>({wireDiameter:w('قطر مفتول','Wire diameter','قطر السلك','Tel çapı'),meanDiameter:w('قطر میانگین حلقه','Mean coil diameter','متوسط قطر الحلقة','Ortalama sarım çapı'),freeLength:w('طول آزاد','Free length','الطول الحر','Serbest uzunluk'),activeCoils:w('حلقه فعال','Active coils','الحلقات الفعالة','Etkin sarım sayısı'),totalCoils:w('حلقه کل','Total coils','إجمالي الحلقات','Toplam sarım'),force:w('نیروی فشاری','Compressive force','قوة الضغط','Basma kuvveti'),shearModulus:w('مدول برشی ماده','Material shear modulus','معامل قص المادة','Malzeme kayma modülü'),allowableStress:w('تنش مجاز معیار قطعه','Part allowable stress','الإجهاد المسموح للقطعة','Parça izin verilen gerilmesi')});
const limits:Record<keyof Inputs,[number,number,string]>={wireDiameter:[0.1,100,'mm'],meanDiameter:[1,10000,'mm'],freeLength:[1,10000,'mm'],activeCoils:[0.25,1000,''],totalCoils:[1,1020,''],force:[0,10000000,'N'],shearModulus:[1000,200000,'MPa'],allowableStress:[1,5000,'MPa']};
function warningLabel(code:string){return ({solid_contact:w('تماس حلقه‌ها؛ مدل خطی در این بار معتبر نیست','Coil contact: the linear model is invalid at this load','تلامس الحلقات؛ النموذج الخطي غير صالح عند هذا الحمل','Sarım teması: doğrusal model bu yükte geçersiz'),allowable_stress_exceeded:w('تنش از حد مجاز واردشده بیشتر است','Stress exceeds the supplied allowable limit','الإجهاد يتجاوز الحد المدخل','Gerilme girilen izin sınırını aşıyor'),spring_index_outside_reference_range:w('شاخص فنر خارج از بازه مرجع ۴ تا ۱۲ است','Spring index is outside reference range 4 to 12','دليل النابض خارج النطاق المرجعي ٤ إلى ١٢','Yay indeksi 4 ile 12 referans aralığının dışında')} as Record<string,string>)[code]||code;}
export default function DigitalTwinWorkspace({user,workspace}:{user:User;workspace:Workspace}){
 const {locale,dir}=useLocale();
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[applied,setApplied]=useState(''),[page,setPage]=useState(1);
 const [recipeId,setRecipeId]=useState(''),[assetId,setAssetId]=useState(''),[title,setTitle]=useState(''),[reason,setReason]=useState(''),[inputs,setInputs]=useState<Inputs>(defaults),[preview,setPreview]=useState<Preview|null>(null),[selected,setSelected]=useState<Scenario|null>(null),[revisions,setRevisions]=useState<any[]>([]),[pins,setPins]=useState<Scenario[]>([]),[saved,setSaved]=useState(false),[sensitivity,setSensitivity]=useState<Preview[]>([]),[parameter,setParameter]=useState<keyof Inputs>('wireDiameter');
 const revision=useRef(0),generation=useRef(0);
 const recipes=workspace.records.filter(r=>r.kind==='recipe'&&r.status==='approved'),assets=workspace.records.filter(r=>r.kind==='asset'&&r.status==='approved');
 async function load(){const token=++generation.current;try{const value=await api<Snapshot>('/twin?'+new URLSearchParams({q:applied,page:String(page),pageSize:'20'}));if(token===generation.current){setData(value);setError('');}}catch(e){if(token===generation.current)setError(depthError(e));}}
 useEffect(()=>{void load();return()=>{generation.current++;};},[applied,page,user.id]);
 function invalidate(){revision.current++;setPreview(null);setSensitivity([]);setSaved(false);}
 function chooseRecipe(id:string){setRecipeId(id);const row=recipes.find(r=>r.id===id);if(row)setInputs(old=>({...old,wireDiameter:Number(row.data.wireDiameter),meanDiameter:Number(row.data.meanDiameter),freeLength:Number(row.data.freeLength),activeCoils:Number(row.data.activeCoils),totalCoils:Number(row.data.activeCoils)+2}));invalidate();}
 async function calculate(){const token=revision.current;setBusy(true);setError('');try{const value=await api<Preview>('/twin/preview','POST',{assetId,recipeId,inputs,scenarioId:selected?.id});if(token===revision.current)setPreview(value);}catch(e){setError(depthError(e));}finally{setBusy(false);}}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');setSaved(false);try{const value=await api<Scenario>(selected?'/twin/'+selected.id:'/twin',selected?'PATCH':'POST',selected?{version:selected.version,title,reason,inputs}:{title,reason,inputs,assetId,recipeId});setSelected(value);setPreview(value);setSaved(true);setRevisions([]);await load();}catch(e){setError(depthError(e));}finally{setBusy(false);}}
 async function open(s:Scenario){revision.current++;setBusy(true);setError('');setSaved(false);try{const value=await api<{scenario:Scenario;revisions:any[]}>('/twin/'+s.id);setSelected(value.scenario);setPreview(value.scenario);setInputs(value.scenario.inputs);setAssetId(value.scenario.assetId);setRecipeId(value.scenario.recipeId);setTitle(value.scenario.title);setReason('');setRevisions(value.revisions);setSensitivity([]);}catch(e){setError(depthError(e));}finally{setBusy(false);}}
 function create(){revision.current++;setSelected(null);setPreview(null);setInputs(defaults);setAssetId('');setRecipeId('');setTitle('');setReason('');setRevisions([]);setSensitivity([]);setSaved(false);}
 async function analyseSensitivity(){const token=revision.current;setBusy(true);setError('');try{const values=await Promise.all([0.95,1.05].map(factor=>api<Preview>('/twin/preview','POST',{assetId,recipeId,inputs:{...inputs,[parameter]:inputs[parameter]*factor},scenarioId:selected?.id})));if(token===revision.current)setSensitivity(values);}catch(e){setError(depthError(e));}finally{setBusy(false);}}
 function exportReport(){if(!preview)return;const rows:any[][]=[[w('پارامتر','Parameter','المعامل','Parametre'),w('مبنا','Baseline','الأساس','Başlangıç'),w('سناریو','Scenario','السيناريو','Senaryo'),w('واحد','Unit','الوحدة','Birim')],...Object.keys(inputs).map(key=>[names()[key as keyof Inputs],preview.baseline.inputs[key as keyof Inputs],inputs[key as keyof Inputs],limits[key as keyof Inputs][2]]),['analysisState',preview===selected?'persisted_revision':'unsaved_preview'],['model','compression-spring-wahl-v1'],['scenario',selected?.id||'preview'],['baseVersion',selected?.version||0],['recipe',preview.reference.recipePart],['recipeRevision',preview.reference.recipeRevision],['asset',preview.reference.assetCode],['rate',preview.baseline.outputs.rate,preview.outputs.rate,'N/mm'],['stress',preview.baseline.outputs.stress,preview.outputs.stress,'MPa'],['validLinear',preview.baseline.outputs.validLinear,preview.outputs.validLinear],['generatedAt',faDateTime(new Date().toISOString())]];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(row=>row.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='fanarlool-twin.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const readOnly=!!selected&&selected.ownerId!==user.id&&user.role!=='admin',writable=!!data?.permissions.write&&!readOnly;
 const metrics:{key:keyof Outputs;label:string;unit:string}[]=[{key:'rate',label:w('سختی فنر','Spring rate','صلابة النابض','Yay rijitliği'),unit:'N/mm'},{key:'stress',label:w('تنش برشی','Shear stress','إجهاد القص','Kayma gerilmesi'),unit:'MPa'},{key:'deflection',label:w('خیز تحت بار','Deflection under load','الانحراف تحت الحمل','Yük altında sehim'),unit:'mm'},{key:'clearance',label:w('فاصله تا تماس حلقه‌ها','Clearance to coil contact','الخلوص قبل تلامس الحلقات','Sarım temasına boşluk'),unit:'mm'},{key:'solidForce',label:w('نیروی تماس حلقه‌ها','Coil contact force','قوة تلامس الحلقات','Sarım temas kuvveti'),unit:'N'},{key:'safetyFactor',label:w('نسبت تنش مجاز به تنش','Allowable-to-actual stress ratio','نسبة الإجهاد المسموح إلى الفعلي','İzin verilen gerilmenin gerçek gerilmeye oranı'),unit:''}];
 const curve=preview?.loadCurve.map(p=>({...p,baselineDeflection:p.baselineValidLinear?p.baselineDeflection:null,candidateDeflection:p.candidateValidLinear?p.candidateDeflection:null}))||[];
 const compression=preview?.outputs.validLinear?Math.max(0,Math.min(0.65,preview.outputs.deflection/inputs.freeLength)):0.65;
 const coilPoints=Array.from({length:65},(_,i)=>`${70+Math.sin(i/64*Math.PI*2*Math.min(inputs.activeCoils,12))*45},${35+i/64*(180*(1-compression))}`).join(' ');
 return <div className="depth-workspace twin-workspace" key={locale}>
 <section className="panel depth-intro"><div><span className="eyebrow">DIGITAL TWIN</span><h2><Layers size={24}/>{w('دوقلوی مهندسی و سناریوهای ساخت','Engineering twin and manufacturing scenarios','التوأم الهندسي وسيناريوهات التصنيع','Mühendislik ikizi ve üretim senaryoları')}</h2><p>{w('پیش از تغییر دستور ساخت، پاسخ فنر را با نسخه تأییدشده مقایسه کنید؛ سناریو، دلیل و بازنگری برای بازبینی مهندسی ثبت می‌شوند.','Compare spring response with the approved recipe before changing production settings. Save scenarios, rationale and revisions for engineering review.','قارن استجابة النابض بوصفة التصنيع المعتمدة قبل تغيير الإعدادات؛ تحفظ السيناريوهات والأسباب والمراجعات للتقييم الهندسي.','Üretim ayarlarını değiştirmeden yay tepkisini onaylı reçeteyle karşılaştırın. Senaryo, gerekçe ve sürümler mühendislik incelemesi için kaydedilir.')}</p></div><button className="secondary" onClick={create} disabled={busy}>{w('سناریوی جدید','New scenario','سيناريو جديد','Yeni senaryo')}</button></section>
 {error&&<div className="notice error" role="alert">{error}</div>}{saved&&<div className="notice success" role="status">{w('سناریو و دلیل در تاریخچه ثبت شدند.','Scenario and rationale were recorded in history.','حفظ السيناريو والسبب في السجل.','Senaryo ve gerekçe geçmişe kaydedildi.')}</div>}
 <div className="depth-columns"><section className="panel twin-editor"><div className="panel-title"><h3><SlidersHorizontal size={20}/>{w('تعریف و تحلیل سناریو','Define and analyse a scenario','تعريف السيناريو وتحليله','Senaryo tanımla ve analiz et')}</h3>{selected&&<span className="badge">v{faNumber(selected.version)}</span>}</div><form onSubmit={save}>
 <div className="form-grid"><label>{w('عنوان سناریو','Scenario title','عنوان السيناريو','Senaryo başlığı')}<input value={title} required minLength={3} maxLength={120} disabled={busy||readOnly} onChange={e=>{setTitle(e.target.value);setSaved(false);}}/></label><label>{w('تجهیز تأییدشده','Approved asset','المعدة المعتمدة','Onaylı ekipman')}<select value={assetId} required disabled={busy||!!selected} onChange={e=>{setAssetId(e.target.value);invalidate();}}><option value="">{w('تجهیز را انتخاب کنید','Select an asset','اختر المعدة','Ekipman seçin')}</option>{assets.map(r=><option key={r.id} value={r.id}>{String(r.data.code||r.data.name||r.id)}</option>)}</select></label><label>{w('دستور ساخت تأییدشده','Approved recipe','وصفة التصنيع المعتمدة','Onaylı üretim reçetesi')}<select value={recipeId} required disabled={busy||!!selected} onChange={e=>chooseRecipe(e.target.value)}><option value="">{w('دستور ساخت را انتخاب کنید','Select a recipe','اختر الوصفة','Reçete seçin')}</option>{recipes.map(r=><option key={r.id} value={r.id}>{String(r.data.part)} · {String(r.data.revision)}</option>)}</select></label></div>
 {(!recipes.length||!assets.length)&&<p className="notice amber">{w('برای تحلیل مرتبط با کارخانه، یک تجهیز و دستور ساخت باید در حوزه مجاز شما تأیید شده باشد.','A permitted asset and recipe must be approved before factory-linked analysis.','يجب اعتماد معدة ووصفة ضمن نطاقك المسموح قبل التحليل المرتبط بالمصنع.','Fabrikaya bağlı analiz için erişiminizdeki bir ekipman ve reçete onaylanmalıdır.')}</p>}
 <div className="form-grid twin-inputs">{(Object.keys(inputs) as (keyof Inputs)[]).map(key=><label key={key}>{names()[key]}<span className="depth-input-unit"><input type="number" required min={key==='totalCoils'?inputs.activeCoils+2:limits[key][0]} max={limits[key][1]} step="any" disabled={busy||readOnly} value={inputs[key]} onChange={e=>{setInputs(old=>({...old,[key]:Number(e.target.value)}));invalidate();}}/><small dir="ltr">{limits[key][2]}</small></span></label>)}</div>
 <label>{w('دلیل تغییر و فرض مهندسی','Change rationale and engineering assumption','سبب التغيير والفرض الهندسي','Değişiklik gerekçesi ve mühendislik varsayımı')}<textarea value={reason} minLength={10} maxLength={1000} required={writable} disabled={busy||readOnly} onChange={e=>setReason(e.target.value)} rows={3}/></label>
 <div className="form-actions"><button className="secondary" type="button" disabled={busy||!recipeId||!assetId} onClick={()=>void calculate()}><RefreshCw size={16}/>{w('تحلیل و مقایسه','Analyse and compare','حلل وقارن','Analiz et ve karşılaştır')}</button>{writable&&<button className="primary" disabled={busy||!preview}><Save size={16}/>{selected?w('ثبت بازنگری','Save revision','حفظ المراجعة','Sürümü kaydet'):w('ذخیره سناریو','Save scenario','حفظ السيناريو','Senaryoyu kaydet')}</button>}</div>
 </form><p className="depth-caption">{w('مبنا، نسخه دستور ساخت هنگام ایجاد سناریو است. نیرو و خواص ماده در هر دو حالت یکسان‌اند؛ ویرایش سناریو مرجع اصلی را بازنویسی نمی‌کند.','The baseline is the recipe snapshot captured at creation. Load and material properties are identical in both cases; edits preserve the original reference.','الأساس نسخة الوصفة عند إنشاء السيناريو. الحمل وخصائص المادة متساوية في الحالتين؛ تحافظ المراجعات على المرجع الأصلي.','Başlangıç, oluşturma anındaki reçete kopyasıdır. Yük ve malzeme özellikleri iki durumda aynıdır; düzenleme ilk referansı korur.')}</p></section>
 <section className="panel twin-result"><div className="panel-title"><h3>{w('پاسخ فنر و حاشیه‌های طراحی','Spring response and design margins','استجابة النابض وهوامش التصميم','Yay tepkisi ve tasarım payları')}</h3><button className="secondary" disabled={!preview} onClick={exportReport}><Download size={16}/>CSV</button></div>
 {!preview?<div className="empty-state"><Layers size={40}/><h3>{w('ابتدا مرجع و بار را مشخص کنید','Select references and load first','حدد المراجع والحمل أولاً','Önce referansları ve yükü seçin')}</h3><p>{w('تحلیل از API محاسبات مهندسی دریافت می‌شود؛ نتیجه ورودی‌های تغییرکرده پس از محاسبه تازه نمایش داده می‌شود.','Engineering results come from the API. Changed inputs require a fresh calculation.','تأتي النتائج الهندسية من API؛ تتطلب المدخلات الجديدة حساباً جديداً.','Mühendislik sonuçları API’den gelir. Değişen girdiler yeni hesap gerektirir.')}</p></div>:<><div className="twin-visual"><svg viewBox="0 0 150 245" role="img" aria-label={w('نمای پاسخ فشاری فنر','Spring compression view','عرض ضغط النابض','Yay basma görünümü')}><line x1="15" y1="25" x2="135" y2="25" stroke="#1f5865" strokeWidth="8"/><polyline points={coilPoints} fill="none" stroke={preview.outputs.validLinear?'#187b76':'#b25a16'} strokeWidth="7" strokeLinejoin="round"/><line x1="15" y1={40+180*(1-compression)} x2="135" y2={40+180*(1-compression)} stroke="#1f5865" strokeWidth="8"/></svg><div><span className={'badge '+(preview.outputs.warnings.length?'rejected':'approved')}>{preview.outputs.warnings.length?w('نیازمند بررسی مهندسی','Engineering review required','يلزم تقييم هندسي','Mühendislik incelemesi gerekli'):w('در حدود واردشده','Within supplied limits','ضمن الحدود المدخلة','Girilen sınırlar içinde')}</span><h4>{preview.reference.recipePart}</h4><p>{preview.reference.assetCode} · {preview.reference.recipeRevision}</p><small>{w('نمای هندسی شماتیک؛ ابعاد با جدول کنترل شوند.','Schematic geometry; verify dimensions in the table.','هندسة تخطيطية؛ تحقق من الأبعاد في الجدول.','Şematik geometri; ölçüleri tabloda doğrulayın.')}</small></div></div>
 <div className="depth-metrics">{metrics.slice(0,4).map(m=><article key={m.key}><span>{m.label}</span><strong>{faNumber(m.key==='deflection'&&!preview.outputs.validLinear?null:preview.outputs[m.key] as number,2)} <small>{m.unit}</small></strong><small>{w('مبنا','Baseline','الأساس','Başlangıç')}: {faNumber(preview.baseline.outputs[m.key] as number,2)}</small></article>)}</div>{preview.outputs.warnings.map(code=><p key={code} className="notice amber">{warningLabel(code)}</p>)}
 <div className="depth-chart" dir="ltr"><ResponsiveContainer width="100%" height={250}><LineChart data={curve}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="force" tickFormatter={v=>faNumber(v)} label={{value:'N',position:'insideBottomRight',offset:-2}}/><YAxis tickFormatter={v=>faNumber(v)} unit=" mm"/><Tooltip formatter={(v:any)=>faNumber(Number(v),2)}/><Legend/><Line dot={false} connectNulls={false} type="linear" dataKey="baselineDeflection" name={w('خیز مبنا','Baseline deflection','انحراف الأساس','Başlangıç sehimi')} stroke="#8495a1" strokeDasharray="5 4"/><Line dot={false} connectNulls={false} type="linear" dataKey="candidateDeflection" name={w('خیز سناریو','Scenario deflection','انحراف السيناريو','Senaryo sehimi')} stroke="#137b76" strokeWidth={3}/></LineChart></ResponsiveContainer></div><p className="depth-caption">{w('نمودار نیرو–خیز فقط تا پیش از تماس حلقه‌ها رسم می‌شود.','The force–deflection curve ends before coil contact.','ينتهي منحنى القوة والانحراف قبل تلامس الحلقات.','Kuvvet–sehim eğrisi sarım temasından önce biter.')}</p></>}
 </section></div>
 {preview&&<section className="panel"><div className="panel-title"><h3><GitCompareArrows size={20}/>{w('مقایسه و حساسیت طراحی','Design comparison and sensitivity','مقارنة التصميم وحساسيته','Tasarım karşılaştırması ve duyarlılığı')}</h3></div><div className="table-scroll"><table><thead><tr><th>{w('شاخص','Metric','المؤشر','Ölçüt')}</th><th>{w('مبنا','Baseline','الأساس','Başlangıç')}</th><th>{w('سناریو','Scenario','السيناريو','Senaryo')}</th><th>{w('تغییر','Change','التغير','Değişim')}</th></tr></thead><tbody>{metrics.map(m=>{const a=preview.baseline.outputs[m.key] as number|null,b=preview.outputs[m.key] as number|null;return <tr key={m.key}><th>{m.label}</th><td>{faNumber(a,2)} {m.unit}</td><td>{m.key==='deflection'&&!preview.outputs.validLinear?'—':faNumber(b,2)} {m.unit}</td><td>{a!==null&&b!==null?faNumber(b-a,2):'—'}</td></tr>;})}</tbody></table></div><div className="depth-toolbar"><label>{w('پارامتر حساسیت ±۵٪','Sensitivity parameter ±5%','معامل الحساسية ±٥٪','Duyarlılık parametresi ±%5')}<select value={parameter} disabled={busy} onChange={e=>{revision.current++;setParameter(e.target.value as keyof Inputs);setSensitivity([]);}}>{(Object.keys(inputs) as (keyof Inputs)[]).filter(k=>!['force','totalCoils'].includes(k)).map(k=><option key={k} value={k}>{names()[k]}</option>)}</select></label><button className="secondary" disabled={busy||readOnly} onClick={()=>void analyseSensitivity()}>{w('اجرای حساسیت','Run sensitivity','تشغيل الحساسية','Duyarlılığı çalıştır')}</button></div>{sensitivity.length===2&&<div className="depth-metrics">{sensitivity.map((s,i)=><article key={i}><span>{names()[parameter]} {i===0?'−5%':'+5%'}</span><strong>{faNumber(s.outputs.rate,2)} N/mm</strong><small>{w('تنش','Stress','الإجهاد','Gerilme')}: {faNumber(s.outputs.stress,2)} MPa</small><small>{w('هشدار','Warnings','التحذيرات','Uyarılar')}: {faNumber(s.outputs.warnings.length)}</small></article>)}</div>}<p className="depth-caption">{w('مدل فنر فشاری استوانه‌ای با رفتار الاستیک و ضریب Wahl است؛ حلقه کل مبنا برابر حلقه فعال به‌علاوه دو فرض می‌شود. برای تغییر دستور ساخت، گواهی ماده، آزمون قطعه و تصویب مهندسی لازم است.','This cylindrical compression spring model uses elastic response and the Wahl correction. Baseline total coils equal active coils plus two. Recipe changes require material certification, part testing and engineering approval.','نموذج نابض ضغط أسطواني باستجابة مرنة وتصحيح Wahl؛ يفترض مجموع حلقات الأساس مساوياً للفعالة مع حلقتين. تغيير الوصفة يتطلب شهادة مادة واختبار القطعة واعتماد الهندسة.','Silindirik basma yayı modeli elastik tepki ve Wahl düzeltmesini kullanır. Başlangıç toplam sarım sayısı etkin sarıma iki eklenerek bulunur. Reçete değişikliği malzeme sertifikası, parça testi ve mühendislik onayı gerektirir.')}</p></section>}
 <section className="panel"><div className="panel-title"><h3><History size={20}/>{w('سناریوهای ثبت‌شده','Saved scenarios','السيناريوهات المحفوظة','Kayıtlı senaryolar')}</h3><button className="secondary" onClick={()=>void load()}><RefreshCw size={16}/>{w('تازه‌سازی','Refresh','تحديث','Yenile')}</button></div><form className="depth-toolbar" onSubmit={e=>{e.preventDefault();setApplied(query);setPage(1);}}><label>{w('جستجوی سناریو','Search scenarios','البحث في السيناريوهات','Senaryo ara')}<input type="search" value={query} onChange={e=>setQuery(e.target.value)} maxLength={120}/></label><button className="secondary"><Search size={16}/>{w('جستجو','Search','بحث','Ara')}</button></form>{data&&<p className="depth-caption">{faNumber(data.total)} {w('سناریو؛ جستجو پیش از صفحه‌بندی','scenarios; search precedes pagination','سيناريو؛ البحث قبل ترقيم الصفحات','senaryo; arama sayfalamadan önce uygulanır')}</p>}<div className="depth-scenario-list">{data?.scenarios.map(s=><article key={s.id}><div><h4>{s.title}</h4><p>{s.reference.recipePart} · {s.reference.assetCode}</p><small>{s.ownerName} · v{faNumber(s.version)} · {faDateTime(s.updatedAt)}</small></div><div className="depth-actions"><button className="secondary" disabled={busy} onClick={()=>void open(s)}>{w('بازکردن و تاریخچه','Open and history','فتح والسجل','Aç ve geçmiş')}</button><button className="secondary" disabled={pins.length>=3&&!pins.some(p=>p.id===s.id)} onClick={()=>setPins(old=>old.some(p=>p.id===s.id)?old.filter(p=>p.id!==s.id):[...old,s])}>{pins.some(p=>p.id===s.id)?w('حذف از مقایسه','Remove comparison','إزالة من المقارنة','Karşılaştırmadan çıkar'):w('افزودن به مقایسه','Compare','قارن','Karşılaştır')}</button></div></article>)}</div>{data&&!data.scenarios.length&&<p className="depth-caption">{w('سناریویی مطابق این جستجو ثبت نشده است.','No saved scenarios match this search.','لا توجد سيناريوهات تطابق البحث.','Aramaya uyan kayıtlı senaryo yok.')}</p>}<div className="depth-actions"><button className="secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>{w('قبلی','Previous','السابق','Önceki')}</button><span>{faNumber(page)}</span><button className="secondary" disabled={!data||page*data.pageSize>=data.total} onClick={()=>setPage(p=>p+1)}>{w('بعدی','Next','التالي','Sonraki')}</button></div>
 {pins.length>0&&<div className="table-scroll"><table><caption>{w('مقایسه حداکثر سه سناریو؛ واحد بار و ماده را بررسی کنید','Compare up to three scenarios; verify load and material units','مقارنة ثلاثة سيناريوهات كحد أقصى؛ تحقق من الحمل ووحدات المادة','En fazla üç senaryoyu karşılaştırın; yük ve malzeme birimlerini kontrol edin')}</caption><thead><tr><th>{w('شاخص','Metric','المؤشر','Ölçüt')}</th>{pins.map(s=><th key={s.id}>{s.title} · v{faNumber(s.version)}</th>)}</tr></thead><tbody>{(['force','shearModulus','allowableStress'] as (keyof Inputs)[]).map(key=><tr key={key}><th>{names()[key]}</th>{pins.map(s=><td key={s.id}>{faNumber(s.inputs[key],2)} {limits[key][2]}</td>)}</tr>)}{metrics.map(m=><tr key={m.key}><th>{m.label} {m.unit}</th>{pins.map(s=><td key={s.id}>{faNumber(m.key==='deflection'&&!s.outputs.validLinear?null:s.outputs[m.key] as number,2)}</td>)}</tr>)}</tbody></table></div>}
 {selected&&<details className="depth-history"><summary>{w('تاریخچه و مرجع نسخه','History and version reference','السجل ومرجع الإصدار','Geçmiş ve sürüm referansı')}</summary><p><code dir="ltr">{selected.id}</code> · {w('مالک','Owner','المسؤول','Sorumlu')}: {selected.ownerName}</p><p>{w('نسخه دستور ساخت','Recipe version','إصدار الوصفة','Reçete sürümü')}: {faNumber(selected.reference.recipeVersion)} · {w('نسخه تجهیز','Asset version','إصدار المعدة','Ekipman sürümü')}: {faNumber(selected.reference.assetVersion)}</p>{revisions.map((r,i)=><article key={r.id||i}><strong>{r.actorName||r.actor_name||'—'}</strong> <time>{(r.createdAt||r.created_at)&&faDateTime(r.createdAt||r.created_at)}</time><p dir="auto">{r.reason||r.details?.reason||r.action}</p></article>)}</details>}
 </section><p className="depth-caption">{w('تحلیل مهندسی قابل تکرار؛ اتصال زنده تجهیزات و تأیید میدانی جداگانه انجام می‌شود. سناریو به PLC فرمان نمی‌دهد و دستور ساخت را خودکار تغییر نمی‌دهد.','Reproducible engineering analysis. Live equipment integration and field validation are separate acceptance steps. Scenarios do not command a PLC or automatically change recipes.','تحليل هندسي قابل للتكرار؛ ربط المعدات والتحقق الميداني خطوات قبول مستقلة. السيناريو لا يرسل أوامر PLC ولا يغير الوصفة تلقائياً.','Tekrarlanabilir mühendislik analizi. Canlı ekipman bağlantısı ve saha doğrulaması ayrı kabul adımlarıdır. Senaryo PLC komutu göndermez veya reçeteyi otomatik değiştirmez.')}</p><span hidden>{dir}</span>
 </div>;
}
