import {Factory,FileCheck,GitBranch,PackageCheck} from 'lucide-react';
import {w} from './copy';
import {useLocale} from './i18n';
export function ExecutionGuide({onOpen}:{onOpen:(page:string)=>void}){
 useLocale();const steps=[
 {icon:Factory,title:w('برنامه را قابل اجرا کنید','Make the plan executable','اجعل الخطة قابلة للتنفيذ','Planı uygulanabilir kılın'),text:w('تولید سفارش را به دستور ساخت و تجهیز تأییدشده متصل می‌کند. مدیر مستقل مقدار و موعد را بررسی و سفارش را آزاد می‌کند؛ سپس بچ با شماره مواد ساخته می‌شود.','Production links an order to an approved recipe and asset. An independent manager reviews quantity and dates and releases the order; a lot is then created with its material lot identifier.','يربط الإنتاج الأمر بوصفة ومعدة معتمدتين. يراجع مدير مستقل الكمية والمواعيد ويطلق الأمر؛ ثم تُنشأ دفعة برقم دفعة موادها.','Üretim emri onaylı reçete ve ekipmana bağlar. Bağımsız yönetici miktar ve tarihleri inceleyip emri serbest bırakır; ardından malzeme parti numarasıyla üretim partisi oluşturulur.')},
 {icon:FileCheck,title:w('کیفیت را پیش از آزادسازی اثبات کنید','Prove quality before release','أثبت الجودة قبل الإطلاق','Serbest bırakmadan önce kaliteyi kanıtlayın'),text:w('پس از پایان بچ، بازرسی همان محصول ثبت و مستقل تأیید می‌شود. نمونه دارای عیب، ابزار منقضی یا عدم انطباق باز مانع آزادسازی است. بازکاری به بازرسی تازه نیاز دارد.','After the lot is finished, an inspection of the same product is recorded and independently approved. Defective samples, expired calibration or an open nonconformance block release. Rework requires fresh inspection evidence.','بعد إنهاء الدفعة، يُسجل فحص المنتج نفسه ويُعتمد بشكل مستقل. تمنع العينات المعيبة أو المعايرة المنتهية أو عدم المطابقة المفتوح إطلاق الدفعة. تتطلب إعادة التشغيل دليلاً جديداً للفحص.','Parti tamamlandıktan sonra aynı ürünün muayenesi kaydedilir ve bağımsız onaylanır. Kusurlu numune, süresi dolmuş kalibrasyon veya açık uygunsuzluk serbest bırakmayı engeller. Yeniden işleme güncel muayene kanıtı gerektirir.')},
 {icon:GitBranch,title:w('اقدام را تا نتیجه پیگیری کنید','Follow action through to its result','تابع الإجراء حتى نتيجته','İşlemi sonuca kadar izleyin'),text:w('درخواست تعمیر یا عدم انطباق تأییدشده به مسئول فعال و موعد مشخص تخصیص می‌یابد. مسئول نتیجه را ثبت می‌کند و شخص مستقل اثربخشی را بررسی می‌کند؛ متن رفع عیب جای تأیید مستقل را نمی‌گیرد.','An approved maintenance request or nonconformance is assigned to an active owner with a due date. The owner records the result and an independent person verifies effectiveness; a resolution note does not substitute for independent verification.','يُسند طلب صيانة أو عدم مطابقة معتمد إلى مسؤول نشط بموعد محدد. يسجل المسؤول النتيجة ويتحقق شخص مستقل من الفعالية؛ لا يحل وصف الإصلاح محل التحقق المستقل.','Onaylı bakım talebi veya uygunsuzluk etkin sorumluya ve tarihe atanır. Sorumlu sonucu kaydeder, bağımsız kişi etkinliği doğrular; çözüm açıklaması bağımsız doğrulamanın yerini almaz.')},
 {icon:PackageCheck,title:w('مواد و نتیجه را قابل ردیابی نگه دارید','Keep materials and results traceable','حافظ على تتبع المواد والنتائج','Malzeme ve sonuçları izlenebilir tutun'),text:w('رسید، مصرف و برگشت به دفتر تغییرناپذیر مواد وارد می‌شوند. مصرف با بچ و ماده دستور ساخت تطبیق داده می‌شود؛ موجودی منفی و برگشت بیشتر از مصرف رد می‌شوند. گزارش، کل شیفت‌های تأییدشده بازه را محاسبه می‌کند.','Receipts, issues and returns enter an immutable material ledger. Issues must match the lot and recipe material; negative stock and returns exceeding issued quantities are rejected. Reports aggregate every approved shift in the period.','تُسجل الاستلامات والصرف والمرتجعات في دفتر مواد غير قابل للتعديل. يجب أن يطابق الصرف الدفعة ومادة الوصفة؛ تُرفض الأرصدة السالبة والمرتجعات الزائدة عن الصرف. تجمع التقارير كل الورديات المعتمدة في الفترة.','Giriş, tüketim ve iadeler değiştirilemez malzeme defterine kaydedilir. Tüketim parti ve reçete malzemesiyle eşleşmelidir; eksi stok ve tüketimi aşan iadeler reddedilir. Raporlar dönemdeki tüm onaylı vardiyaları toplar.')}
 ];
 return <section className="ops-panel execution-guide"><div className="ops-panel-title"><div><span className="section-kicker">{w('مسیر استفاده روزانه','DAILY OPERATING JOURNEY','مسار التشغيل اليومي','GÜNLÜK OPERASYON AKIŞI')}</span><h2>{w('از سفارش تا محصول قابل آزادسازی','From order to releasable product','من الأمر إلى منتج قابل للإطلاق','Emirden serbest bırakılabilir ürüne')}</h2></div><button className="primary" onClick={()=>onOpen('execution')}>{w('ورود به اجرای کارخانه','Open factory execution','فتح تنفيذ المصنع','Fabrika yürütmeyi aç')}</button></div><ol className="execution-guide-steps">{steps.map((step,i)=><li key={i}><step.icon size={22}/><div><h3>{step.title}</h3><p>{step.text}</p></div></li>)}</ol><p className="panel-explainer">{w('ارزش اقتصادی از حذف مصرف بی‌سند، کاهش ارسال محصول بدون شاهد کیفیت و کوتاه‌شدن زمان پیگیری اقدام حاصل می‌شود. میزان صرفه‌جویی باید با خط پایه واقعی کارخانه و گزارش ماهانه سنجیده شود.','Economic value comes from eliminating undocumented consumption, reducing product release without quality evidence and shortening action follow-up time. Savings must be measured against the factory’s actual baseline and monthly reports.','تأتي القيمة الاقتصادية من منع الاستهلاك غير الموثق وتقليل إطلاق المنتجات دون دليل جودة وتقليص وقت متابعة الإجراءات. يجب قياس الوفورات مقابل خط الأساس الفعلي للمصنع والتقارير الشهرية.','Ekonomik değer belgesiz tüketimin önlenmesinden, kalite kanıtı olmadan ürün çıkışının azalmasından ve işlem takip süresinin kısalmasından gelir. Tasarruflar fabrikanın gerçek başlangıç verileri ve aylık raporlarla ölçülmelidir.')}</p><button className="secondary" onClick={()=>onOpen('reports')}>{w('گزارش عملکرد و سوابق','Performance reports and archive','تقارير الأداء والأرشيف','Performans raporları ve arşiv')}</button></section>;
}
