import {useState} from 'react';
import {useLocale, type Language} from './i18n';

type Words = readonly [string, string, string, string];
const w = (fa: string, en: string, ar: string, tr: string): Words => [fa, en, ar, tr];
type Action = {key: string; label: Words};
type Article = {id: string; title: Words; summary: Words; purpose: Words; steps: Words[]; method: Words; formula?: string; decision: Words; evidence: Words; actions: Action[]};
const action = (key: string, label: Words): Action => ({key, label});
const articles: Article[] = [
  {
    id: 'start',
    title: w('شروع کار و مسئولیت نقش‌ها', 'Getting started and role responsibilities', 'البدء ومسؤوليات الأدوار', 'Başlangıç ve rol sorumlulukları'),
    summary: w('مسیر روزانه هشت نقش، حساب شخصی و انتخاب حوزه کاری.', 'Daily paths for eight roles, personal accounts and work areas.', 'المسارات اليومية للأدوار الثمانية والحسابات ومجالات العمل.', 'Sekiz rolün günlük akışı, kişisel hesaplar ve çalışma alanları.'),
    purpose: w('پلتفرم چرخه تولید فنر را از دستور ساخت و مواد تا شیفت، کیفیت، نگهداری و انرژی به سوابق قابل بررسی تبدیل می‌کند. هر کار را با شناسه ثابت بچ، قطعه، ابزار یا تجهیز شروع کنید و همان شناسه را در حوزه مرتبط به کار ببرید.', 'The platform turns the spring production cycle—from recipes and materials to shifts, quality, maintenance and energy—into reviewable records. Start with a stable batch, part, instrument or asset ID and reuse it in related areas.', 'تحوّل المنصة دورة إنتاج النوابض من التصنيع والمواد إلى الورديات والجودة والصيانة والطاقة إلى سجلات قابلة للمراجعة. ابدأ بمعرّف ثابت للدفعة أو القطعة أو الأداة أو المعدة واستخدمه في المجالات المرتبطة.', 'Platform; reçete ve malzemeden vardiya, kalite, bakım ve enerjiye kadar yay üretimini incelenebilir kayıtlara dönüştürür. Sabit parti, parça, cihaz veya ekipman kimliğiyle başlayın ve ilgili alanlarda aynı kimliği kullanın.'),
    steps: [
      w('با حساب شخصی نقش خود وارد شوید؛ پروفایل، زبان و تنظیمات را بررسی کنید. برای کار کارخانه از حساب عملیاتی استفاده کنید؛ حساب‌های نمایشی فضای داده جداگانه دارند.', 'Sign in with your personal role account; review profile, language and settings. Use operational accounts for factory work; demonstration accounts have a separate data space.', 'ادخل بحسابك الشخصي وراجع الملف واللغة والتفضيلات. استخدم الحساب التشغيلي للمصنع؛ لحسابات العرض مساحة بيانات منفصلة.', 'Kişisel rol hesabınızla giriş yapın; profil, dil ve ayarları kontrol edin. Fabrika için operasyonel hesap kullanın; gösterim hesaplarının verileri ayrıdır.'),
      w('حوزه مرتبط با مسئولیت خود را انتخاب کنید. مشاهده، ثبت و تأیید مطابق مجوز حساب در سرور کنترل می‌شود؛ تغییر زبان مجوز را تغییر نمی‌دهد.', 'Choose the area for your responsibility. The server enforces viewing, writing and approval permissions; changing language does not change access.', 'اختر مجال مسؤوليتك. يفرض الخادم صلاحيات العرض والتسجيل والاعتماد؛ ولا يغيّر تبديل اللغة الصلاحيات.', 'Görevinize uygun alanı seçin. Görüntüleme, kayıt ve onay izinlerini sunucu uygular; dil değişikliği izinleri değiştirmez.'),
      w('پس از ثبت، شناسه و وضعیت رکورد را در سوابق کنترل کنید. در قطع ارتباط، قبل از ایجاد دوباره، وجود ثبت قبلی را بررسی کنید.', 'After saving, check the record ID and status. If the connection drops, look for the previous save before creating another record.', 'بعد الحفظ، تحقّق من معرّف السجل وحالته. عند انقطاع الاتصال ابحث عن التسجيل السابق قبل إنشاء آخر.', 'Kaydettikten sonra kayıt kimliği ve durumunu kontrol edin. Bağlantı kesilirse yeniden oluşturmadan önce önceki kaydı arayın.'),
    ],
    method: w('داده معتبر به شناسه روشن، واحد، زمان، ثبت‌کننده مسئول و تأیید مستقل نیاز دارد. تاریخ ورودی و نمایش شمسی است؛ زمان فنی سرور برای ردیابی حفظ می‌شود.', 'Reliable data needs a clear ID, unit, time, responsible author and independent approval. Input and display dates use the Persian calendar; technical server timestamps remain available for tracing.', 'تحتاج البيانات الموثوقة إلى معرّف ووحدة ووقت ومسؤول واعتماد مستقل. تستخدم تواريخ الإدخال والعرض التقويم الفارسي، وتُحفظ أوقات الخادم للتتبّع.', 'Güvenilir veri; kimlik, birim, zaman, sorumlu kayıt sahibi ve bağımsız onay gerektirir. Giriş ve gösterim tarihleri İran takvimindedir; teknik sunucu zamanları izleme için korunur.'),
    decision: w('اگر حوزه‌ای برای حساب شما در دسترس نیست، درخواست دسترسی را به مدیر سامانه بدهید. برای تحویل شیفت، رکوردهای باز و مسئول پیگیری را مشخص کنید.', 'If an area is unavailable, request access from the administrator. Identify open records and their owners for shift handover.', 'إذا لم يتوفر مجال لحسابك فاطلب الصلاحية من المدير. حدّد السجلات المفتوحة والمسؤولين عنها عند تسليم الوردية.', 'Bir alan kullanılamıyorsa yöneticiden erişim isteyin. Vardiya tesliminde açık kayıtları ve sorumlularını belirleyin.'),
    evidence: w('فعالیت شخصی در صفحه فعالیت و رخدادهای سراسری در پایش مدیر سامانه بررسی می‌شود. گزارش قابل اتکا، وضعیت ثبت و تأیید را همراه نتیجه نشان می‌دهد.', 'Personal actions are reviewed in Activity and system-wide events in administrator monitoring. A reliable report includes recording and approval status with the result.', 'تُراجع الأعمال الشخصية في النشاط والأحداث العامة في مراقبة المدير. يعرض التقرير الموثوق حالة التسجيل والاعتماد مع النتيجة.', 'Kişisel işlemler Etkinlikte, genel olaylar yönetici izlemesinde incelenir. Güvenilir rapor sonucu kayıt ve onay durumuyla sunar.'),
    actions: [action('profile', w('پروفایل من', 'My profile', 'ملفي', 'Profilim')), action('activity', w('فعالیت‌های من', 'My activity', 'نشاطي', 'Etkinliklerim'))],
  },
  {
    id: 'approval',
    title: w('ثبت، بررسی و تأیید مستقل', 'Recording, review and independent approval', 'التسجيل والمراجعة والاعتماد المستقل', 'Kayıt, inceleme ve bağımsız onay'),
    summary: w('گردش پیش‌نویس تا تأیید و جداسازی ثبت‌کننده از تأییدکننده.', 'Draft-to-approval workflow and separation of author and approver.', 'المسار من المسودة إلى الاعتماد وفصل صاحب السجل عن المعتمِد.', 'Taslak-onay akışı ve kayıt sahibi ile onaylayanın ayrılması.'),
    purpose: w('رکورد سند یک رویداد مشخص است. پیش‌نویس برای آماده‌سازی، ارسال برای بررسی شخص دوم و تأیید برای پذیرش مسئولانه داده است. داشبورد بهره‌وری فقط رکوردهای تأییدشده تولید را تجمیع می‌کند.', 'A record documents a specific event. A draft prepares data, submission requests a second-person review, and approval accepts responsibility for it. Productivity aggregates approved production records only.', 'يوثّق السجل حدثاً محدداً. المسودة لإعداد البيانات، والإرسال لمراجعة شخص ثانٍ، والاعتماد لقبولها بمسؤولية. تجمع الإنتاجية سجلات الإنتاج المعتمدة فقط.', 'Kayıt belirli bir olayı belgeler. Taslak veriyi hazırlar, gönderme ikinci kişi incelemesini ister, onay sorumlu kabulü ifade eder. Verimlilik yalnızca onaylı üretim kayıtlarını toplar.'),
    steps: [
      w('پیش‌نویس بسازید و فیلدهای الزامی، واحد، شناسه و تاریخ را وارد کنید. تعداد سالم از کل و زمان کارکرد از زمان برنامه بیشتر نباشد.', 'Create a draft with required fields, units, ID and date. Good count must not exceed total; runtime must not exceed planned time.', 'أنشئ مسودة بالحقول المطلوبة والوحدات والمعرّف والتاريخ. لا يتجاوز السليم الكلي ولا التشغيل الوقت المخطط.', 'Zorunlu alan, birim, kimlik ve tarihle taslak oluşturun. Sağlam adet toplamı, çalışma süresi planı aşmamalıdır.'),
      w('با منبع اولیه تطبیق دهید و برای بررسی ارسال کنید. شرح عیب، توقف یا اصلاح را روشن بنویسید؛ عدد بدون روش و واحد برای تصمیم کافی نیست.', 'Reconcile with the original source and submit. Describe defects, stops or corrections clearly; a number without a method and unit is insufficient.', 'طابق المصدر الأصلي وأرسل للمراجعة. صف العيب أو التوقف أو التصحيح بوضوح؛ الرقم دون طريقة ووحدة لا يكفي.', 'İlk kaynakla karşılaştırıp gönderin. Kusur, duruş veya düzeltmeyi açık yazın; yöntem ve birimi olmayan sayı yeterli değildir.'),
      w('شخص دیگر با مجوز تأیید، هویت بچ و شواهد را کنترل و تأیید یا رد کند. ثبت‌کننده، حتی مدیر سامانه، نمی‌تواند رکورد خود را تأیید کند.', 'A different authorized person checks batch identity and evidence, then approves or rejects. The author, even an administrator, cannot approve their own record.', 'يتحقق شخص آخر مخوّل من هوية الدفعة والأدلة ثم يعتمد أو يرفض. لا يستطيع صاحب السجل، حتى المدير، اعتماد سجله.', 'Yetkili başka kişi parti kimliğini ve kanıtı kontrol edip onaylar veya reddeder. Yönetici dâhil kayıt sahibi kendi kaydını onaylayamaz.'),
    ],
    formula: 'draft → submitted → approved / rejected',
    method: w('نسخه رکورد تغییر هم‌زمان را تشخیص می‌دهد. در تعارض نسخه، دوباره بارگیری و اختلاف را بررسی کنید؛ ارسال مجدد کورکورانه نکنید.', 'Record versions detect concurrent changes. On a version conflict, reload and review the difference instead of blindly resubmitting.', 'تكشف إصدارات السجل التغييرات المتزامنة. عند تعارض الإصدار أعد التحميل وراجع الفرق ولا تعِد الإرسال بلا فحص.', 'Kayıt sürümleri eşzamanlı değişikliği algılar. Sürüm çakışmasında yeniden yükleyip farkı inceleyin; körlemesine tekrar göndermeyin.'),
    decision: w('تأیید جای آزمون یا گواهی نیست. ابزار نامعتبر، داده متناقض یا شواهد ناکافی دلیل رد و ثبت علت است؛ اقدام اصلاحی را در NCR پیگیری کنید.', 'Approval does not replace testing or certification. Invalid instruments, conflicting data or inadequate evidence require rejection with a reason; track corrective action in an NCR.', 'الاعتماد لا يحل محل الاختبار أو الشهادة. الأداة غير الصالحة أو التعارض أو نقص الدليل يستوجب الرفض مع السبب، وتُتابع المعالجة في NCR.', 'Onay test veya sertifikanın yerini almaz. Geçersiz cihaz, çelişki veya yetersiz kanıtta nedeni ile reddedin; düzeltmeyi NCR üzerinden izleyin.'),
    evidence: w('خروجی سوابق را با شناسه و وضعیت بخوانید. پیش‌نویس، در انتظار بررسی و تأییدشده را جدا گزارش کنید؛ تأییدنشده عملکرد قطعی نیست.', 'Read record exports with IDs and statuses. Report draft, pending and approved records separately; unapproved data is not confirmed performance.', 'اقرأ المخرجات مع المعرّفات والحالات. افصل المسودة والمعلّقة والمعتمدة؛ البيانات غير المعتمدة ليست أداءً مؤكداً.', 'Çıktıları kimlik ve durumuyla okuyun. Taslak, bekleyen ve onaylı kayıtları ayrı raporlayın; onaysız veri kesin performans değildir.'),
    actions: [action('production', w('سوابق تولید', 'Production records', 'سجلات الإنتاج', 'Üretim kayıtları')), action('ncr', w('عدم انطباق', 'Nonconformities', 'عدم المطابقة', 'Uygunsuzluklar'))],
  },
  {
    id: 'production',
    title: w('تولید، مواد و بهره‌وری شیفت', 'Production, materials and shift productivity', 'الإنتاج والمواد وإنتاجية الوردية', 'Üretim, malzeme ve vardiya verimliliği'),
    summary: w('ثبت بچ و مواد؛ تفسیر OEE و یافتن عامل افت.', 'Record batches and materials; interpret OEE and locate losses.', 'تسجيل الدفعات والمواد وتفسير OEE وتحديد الخسارة.', 'Parti ve malzeme kaydı; OEE yorumu ve kayıp tespiti.'),
    purpose: w('تولید، خروجی سالم و ضایعات را با زمان و سیکل مرجع مرتبط می‌کند. مواد و قطعات یدکی، موجودی، حد سفارش و شماره ذوب/بچ تأمین را نگه می‌دارد تا کمبود و اختلاط مواد دیده شود.', 'Production links good output and scrap to time and reference cycle. Materials and spares hold stock, reorder limits and heat/supply-lot numbers to expose shortages and mix-ups.', 'يربط الإنتاج السليم والهالك بالوقت والدورة المرجعية. تحفظ المواد وقطع الغيار المخزون وحد الطلب ورقم الصهرة أو التوريد لكشف النقص والخلط.', 'Üretim sağlam çıktı ve hurdayı süre ve referans çevrimle ilişkilendirir. Malzeme/yedek parça alanı stok, sipariş eşiği ve döküm/tedarik partisini tutarak eksik ve karışıklığı görünür kılar.'),
    steps: [
      w('پیش از شیفت کد محصول و بازنگری نسخه ساخت را کنترل کنید؛ بچ را به شماره ذوب مواد مرتبط و موجودی/حد سفارش را بررسی کنید.', 'Before the shift, check product code and recipe revision; link the batch to material heat and review stock/reorder limits.', 'قبل الوردية راجع رمز المنتج وإصدار التصنيع، واربط الدفعة بصهرة المادة وافحص المخزون وحد الطلب.', 'Vardiya öncesi ürün ve reçete revizyonunu kontrol edin; partiyi malzeme dökümüne bağlayıp stok/eşiği inceleyin.'),
      w('زمان برنامه، کارکرد، سیکل ایده‌آل، کل و سالم همان شیفت را ثبت کنید. سیکل برای همان محصول و خط معتبر باشد و علت توقف ثبت شود.', 'Record planned/runtime minutes, ideal cycle and total/good counts for that shift. The cycle must apply to the product and line; record stop reasons.', 'سجّل زمن الخطة والتشغيل والدورة والعدد الكلي والسليم للوردية نفسها. يجب أن تنطبق الدورة على المنتج والخط مع سبب التوقف.', 'Aynı vardiya için plan/çalışma süresi, ideal çevrim ve toplam/sağlamı kaydedin. Çevrim ürün ve hatta uygun olsun; duruş nedenini yazın.'),
      w('پس از تأیید، مؤلفه افت OEE را پیدا کنید: دسترس‌پذیری به نگهداری، کیفیت به بازرسی/NCR و عملکرد به بررسی سیکل و فرآیند ارجاع شود.', 'After approval, locate the OEE loss: route availability to maintenance, quality to inspection/NCR, and performance to cycle/process review.', 'بعد الاعتماد حدّد خسارة OEE: الإتاحة للصيانة والجودة للتفتيش أو NCR والأداء لمراجعة الدورة والعملية.', 'Onay sonrası OEE kaybını bulun: kullanılabilirliği bakıma, kaliteyi muayene/NCR’ye, performansı çevrim/süreç incelemesine yönlendirin.'),
    ],
    formula: 'A = run / planned · P = idealCycle(s) × total / (run(min) × 60) · Q = good / total · OEE = A × P × Q',
    method: w('ضایعات = کل − سالم. در تجمیع، صورت و مخرج زمان/تعداد جمع می‌شوند؛ میانگین ساده OEE شیفت‌ها معتبر نیست. تولید یا کارکرد صفر می‌تواند مؤلفه را تعریف‌نشده کند.', 'Scrap = total − good. Aggregation combines time/count numerators and denominators; averaging shift OEE percentages is unreliable. Zero production/runtime can leave a component undefined.', 'الهالك = الكلي − السليم. تُجمع البسوط والمقامات الزمنية والعددية؛ متوسط نسب OEE للورديات غير موثوق. قد يجعل الصفر مكوّناً غير معرّف.', 'Hurda = toplam − sağlam. Toplam hesap süre/adet pay ve paydalarını birleştirir; vardiya OEE ortalaması güvenilir değildir. Sıfır üretim/çalışma bir bileşeni tanımsız bırakabilir.'),
    decision: w('موجودی زیر حد سفارش نیازمند پیگیری تأمین است؛ ثبت موجودی جای شمارش انبار یا اتصال ERP نیست. بهبود OEE را به اقدام و هزینه واقعی افت مربوط کنید.', 'Stock below its threshold needs procurement follow-up; records do not replace physical counts or provide ERP integration. Link OEE improvements to actions and actual loss costs.', 'المخزون دون الحد يحتاج متابعة التوريد؛ السجل لا يحل محل الجرد ولا يوفّر ربط ERP. اربط تحسّن OEE بالإجراء وتكلفة الخسارة الفعلية.', 'Eşik altı stok tedarik takibi ister; kayıt fiziksel sayım veya ERP entegrasyonu değildir. OEE iyileşmesini eylem ve gerçek kayıp maliyetine bağlayın.'),
    evidence: w('خروجی: رکورد شیفت تأییدشده، علت توقف، بچ/ذوب و مقایسه دوره‌های همسان. درصد بهتر به‌تنهایی اثبات افزایش سود نیست.', 'Output: approved shift, stop reason, batch/heat and comparable periods. A better percentage alone does not prove profit growth.', 'المخرج: وردية معتمدة وسبب توقف ودفعة/صهرة وفترات متكافئة. النسبة الأفضل وحدها لا تثبت زيادة الربح.', 'Çıktı: onaylı vardiya, duruş nedeni, parti/döküm ve karşılaştırılabilir dönem. İyi yüzde tek başına kâr artışını kanıtlamaz.'),
    actions: [action('production', w('ثبت تولید', 'Record production', 'تسجيل الإنتاج', 'Üretim kaydı')), action('inventory', w('مواد و قطعات', 'Materials and spares', 'المواد والقطع', 'Malzeme ve parçalar')), action('lab:oee', w('محاسبه OEE', 'Calculate OEE', 'حساب OEE', 'OEE hesapla'))],
  },
  {
    id: 'quality',
    title: w('کیفیت، اندازه‌گیری و عدم انطباق', 'Quality, measurement and nonconformity', 'الجودة والقياس وعدم المطابقة', 'Kalite, ölçüm ve uygunsuzluk'),
    summary: w('بازرسی بچ، اعتبار ابزار و کنترل اثربخشی اقدام اصلاحی.', 'Batch inspection, instrument validity and corrective-action effectiveness.', 'تفتيش الدفعات وصلاحية الأدوات وفاعلية التصحيح.', 'Parti muayenesi, cihaz geçerliliği ve düzeltme etkinliği.'),
    purpose: w('بازرسی نتیجه را به بچ و ابزار وصل می‌کند. کالیبراسیون مرجع گواهی، اعتبار و عدم قطعیت را ثبت می‌کند. NCR مهار، علت ریشه‌ای، مسئول و مهلت اقدام را قابل پیگیری نگه می‌دارد.', 'Inspection links results to the batch/instrument. Calibration records certificate reference, validity and uncertainty. NCRs track containment, root cause, owner and deadline.', 'يربط التفتيش النتيجة بالدفعة والأداة. تسجّل المعايرة مرجع الشهادة والصلاحية وعدم اليقين. يتتبّع NCR الاحتواء والسبب والمسؤول والمهلة.', 'Muayene sonucu parti/cihaza bağlar. Kalibrasyon sertifika, geçerlilik ve belirsizliği kaydeder. NCR kontrol altına alma, kök neden, sorumlu ve tarihi izler.'),
    steps: [
      w('گواهی و تاریخ ابزار، واحد و معیار نقشه/قرارداد را کنترل کنید؛ مقدار اسمی و تلرانس را از مرجع مصوب بگیرید.', 'Check instrument certificate/date, unit and drawing/contract limits; use approved nominal values and tolerances.', 'راجع شهادة الأداة وتاريخها والوحدة وحدود الرسم أو العقد، واستخدم القيم والتفاوتات المعتمدة.', 'Cihaz sertifika/tarihini, birimi ve çizim/sözleşme sınırını kontrol edin; onaylı nominal ve toleransı kullanın.'),
      w('نمونه، معیوب، میانگین، پارامتر، ابزار و روش را ثبت کنید. برای SPC اندازه‌های منفرد را به ترتیب زمان بدهید؛ میانگین بچ جای سری زمانی نیست.', 'Record samples, defects, mean, parameter, instrument and method. SPC needs time-ordered individual values; a batch mean is not a time series.', 'سجّل العينات والعيوب والمتوسط والمعلمة والأداة والطريقة. يحتاج SPC قياسات فردية زمنية؛ متوسط الدفعة ليس سلسلة زمنية.', 'Numune, kusur, ortalama, parametre, cihaz ve yöntemi yazın. SPC zaman sıralı tekil değer ister; parti ortalaması zaman serisi değildir.'),
      w('در مغایرت، طبق رویه کارخانه بچ مشکوک را مهار و NCR با مسئول و مهلت بسازید؛ بررسی شخص دوم و نمونه پس از اصلاح، اثربخشی را روشن کند.', 'Contain suspect batches under factory procedure and create an owned, dated NCR; second-person review and post-correction sampling assess effectiveness.', 'احتوِ الدفعة وفق إجراء المصنع وأنشئ NCR بمسؤول ومهلة؛ وتقيّم مراجعة شخص ثانٍ وعينات بعد التصحيح الفاعلية.', 'Şüpheli partiyi prosedüre göre kontrol altına alıp sorumlu/tarihli NCR açın; ikinci kişi incelemesi ve düzeltme sonrası örnek etkinliği belirler.'),
    ],
    formula: 'defect rate = defects / samples · limits = nominal ± tolerance · Cp = (USL − LSL) / (6σwithin) · Cpk = min(USL − mean, mean − LSL) / (3σwithin)',
    method: w('کیفیت بازه Wilson دوطرفه ۹۵٪ دارد. SPC، σ درون‌فرآیند را از I–MR و Pp/Ppk را از انحراف معیار کل نمونه می‌گیرد. هشدار ابزار زیر ۳۰ اندازه، برآورد مقدماتی است؛ تفسیر قابلیت به پایداری، استقلال نمونه‌ها و بررسی فرض توزیع نیاز دارد.', 'Quality uses a two-sided 95% Wilson interval. SPC estimates within σ from I–MR and Pp/Ppk from overall sample deviation. The tool flags fewer than 30 values as preliminary; capability interpretation requires stability, independent samples and distribution-assumption review.', 'تستخدم الجودة فاصل Wilson ثنائي الطرف ٩٥٪. يقدّر SPC الانحراف الداخلي من I–MR وPp/Ppk من انحراف العينة الكلي. تصنّف الأداة أقل من ٣٠ قيمة كتقدير أولي؛ وتحتاج القابلية استقراراً وعينات مستقلة وفحص افتراض التوزيع.', 'Kalite iki taraflı %95 Wilson aralığını kullanır. SPC iç σ’yı I–MR’den, Pp/Ppk’yı toplam örnek sapmasından alır. Araç 30’dan az değeri ön tahmin sayar; yeterlilik yorumu kararlılık, bağımsız örnek ve dağılım varsayımı incelemesi gerektirir.'),
    decision: w('اندازه ± عدم قطعیت را با تلرانس بسنجید. حد بالای Wilson بالاتر از سقف عیب منتخب نیازمند بررسی است. محاسبه جای طرح نمونه‌برداری مصوب، گواهی یا تصمیم مسئول کیفیت نیست.', 'Compare measurement ± uncertainty with tolerance. Wilson upper bounds above the chosen defect ceiling require review. Calculation does not replace approved sampling, certification or quality-owner decisions.', 'قارن القياس ± عدم اليقين بالتفاوت. الحد الأعلى لـWilson فوق سقف العيب المختار يستدعي الفحص. الحساب لا يحل محل خطة عينات معتمدة أو شهادة أو قرار مسؤول الجودة.', 'Ölçüm ± belirsizliği toleransla karşılaştırın. Wilson üst sınırı seçilen kusur eşiğini aşarsa inceleyin. Hesap onaylı örnekleme, sertifika veya kalite kararı yerine geçmez.'),
    evidence: w('پرونده بچ به بازرسی، ابزار و NCR مرتبط شود. ثبت شماره گواهی، صدور یا اعتبارسنجی خودکار آن نیست؛ اصل گواهی و روش در منابع کنترل‌شده کارخانه نگهداری شود.', 'Link batch, inspection, instrument and NCR. Recording a certificate number does not issue or automatically validate it; retain original certificates/methods in factory-controlled sources.', 'اربط الدفعة والتفتيش والأداة وNCR. تسجيل رقم الشهادة لا يصدرها ولا يتحقق منها تلقائياً؛ احفظ الأصل والطريقة في مصادر المصنع المضبوطة.', 'Parti, muayene, cihaz ve NCR’yi bağlayın. Sertifika numarası kaydı sertifikayı düzenlemez veya otomatik doğrulamaz; asıl belge/yöntemi kontrollü kaynakta tutun.'),
    actions: [action('inspection', w('بازرسی کیفیت', 'Quality inspection', 'تفتيش الجودة', 'Kalite muayenesi')), action('calibration', w('کالیبراسیون', 'Calibration', 'المعايرة', 'Kalibrasyon')), action('ncr', w('عدم انطباق', 'Nonconformities', 'عدم المطابقة', 'Uygunsuzluklar')), action('lab:spc', w('تحلیل SPC', 'SPC analysis', 'تحليل SPC', 'SPC analizi'))],
  },
  {
    id: 'maintenance',
    title: w('تجهیزات و نگهداری مبتنی بر وضعیت', 'Assets and condition-based maintenance', 'المعدات والصيانة حسب الحالة', 'Ekipman ve durum temelli bakım'),
    summary: w('شناسنامه، دستورکار و تفسیر سیگنال واقعی ارتعاش ورودی.', 'Asset registers, work orders and supplied vibration signals.', 'سجلات المعدات وأوامر العمل وإشارات الاهتزاز المدخلة.', 'Ekipman kartları, iş emirleri ve girilen titreşim sinyali.'),
    purpose: w('شناسه تجهیز، شناسنامه، دستورکار و توقف تولید را متصل می‌کند. شناسنامه محل، بحرانی‌بودن، دوره سرویس و منبع قطعه را دارد؛ دستورکار علامت را به اولویت، موعد و شرح رفع عیب تبدیل می‌کند.', 'An asset ID connects register, work orders and production stops. Registers contain location, criticality, service interval and spare source; work orders turn symptoms into priority, due date and resolution.', 'يربط معرّف المعدة سجلها وأوامر العمل والتوقفات. يشمل السجل الموقع والأهمية والخدمة ومصدر القطع، ويحوّل أمر العمل العارض إلى أولوية وموعد وحل.', 'Ekipman kimliği kartı, iş emrini ve duruşu bağlar. Kart konum, kritiklik, servis aralığı ve parça kaynağını; iş emri belirti, öncelik, tarih ve çözümü içerir.'),
    steps: [
      w('محل واقعی و دوره سرویس سازنده را ثبت کنید؛ تجهیز بحرانی و قطعه با تأمین طولانی را مشخص و حد سفارش قطعه را بررسی کنید.', 'Record actual location and manufacturer interval; identify critical assets/long-lead spares and check reorder levels.', 'سجّل الموقع الفعلي وفترة خدمة المصنّع وحدّد المعدات الحرجة والقطع طويلة التوريد وراجع حد الطلب.', 'Gerçek konum ve üretici aralığını yazın; kritik ekipman/uzun tedarikli parçaları belirleyip sipariş eşiğini kontrol edin.'),
      w('برای علامت غیرعادی، دستورکار با تجهیز، اولویت و موعد بسازید؛ توقف و رفع عیب واقعی را ثبت و برای بررسی مستقل ارسال کنید.', 'Create a work order for abnormal symptoms with asset, priority and due date; record actual downtime/resolution and submit for independent review.', 'أنشئ أمر عمل للعارض غير الطبيعي بالمعدة والأولوية والموعد وسجّل التوقف والحل الفعلي للمراجعة المستقلة.', 'Anormal belirtide ekipman, öncelik ve tarihli iş emri açın; gerçek duruş/çözümü yazıp bağımsız incelemeye gönderin.'),
      w('در PdM سری سرعت ارتعاش mm/s و خط مبنای هم‌شرایط وارد کنید؛ بار، سرعت، محل و نصب حسگر را در تفسیر لحاظ و تصمیم را در دستورکار ثبت کنید.', 'Enter mm/s velocity series and a comparable baseline in PdM; account for load, speed, sensor position/mounting and record the decision in the work order.', 'أدخل سلسلة السرعة mm/s وخط أساس مماثلاً في PdM، وفسّر مع الحمل والسرعة وموضع الحساس وتثبيته وسجّل القرار في الأمر.', 'PdM’ye mm/s hız serisi ve eşdeğer referans girin; yük, hız, sensör konumu/montajını dikkate alıp kararı iş emrine yazın.'),
    ],
    formula: 'AC = x − mean(x) · RMS = √mean(AC²) · crest factor = max(|AC|) / RMS · ratio = RMS / baseline',
    method: w('AC RMS پس از حذف میانگین است؛ ضریب قله برای RMS صفر تعریف‌نشده است. افزایش نسبت خط مبنا نیازمند بررسی است و آستانه باید با سازنده و شرایط ماشین تعیین شود.', 'AC RMS removes the mean; crest factor is undefined at zero RMS. A higher baseline ratio needs review; thresholds depend on the manufacturer and machine conditions.', 'يزيل AC RMS المتوسط، وعامل القمة غير معرّف عند الصفر. ارتفاع نسبة الأساس يحتاج مراجعة، وتُحدّد الحدود حسب المصنّع وظروف المعدة.', 'AC RMS ortalamayı çıkarır; RMS sıfırsa tepe faktörü tanımsızdır. Referans oranı artışı inceleme ister; eşik üretici ve makine koşuluna bağlıdır.'),
    decision: w('این ابزار شاخص سیگنال محاسبه می‌کند؛ FFT، تشخیص خودکار عیب یا عمر باقی‌مانده ندارد. خطر ایمنی با رویه توقف و ایمن‌سازی کارخانه مدیریت شود.', 'The tool computes signal indicators, not FFT, automatic fault diagnosis or remaining life. Manage safety risks through factory shutdown/isolation procedures.', 'تحسب الأداة مؤشرات الإشارة ولا تقدّم FFT أو تشخيصاً آلياً أو عمراً متبقياً. تُدار مخاطر السلامة بإجراءات الإيقاف والعزل.', 'Araç sinyal göstergesi hesaplar; FFT, otomatik tanı veya kalan ömür sunmaz. Güvenlik riskini durdurma/izolasyon prosedürüyle yönetin.'),
    evidence: w('اثر نگهداری با توقف هم‌شرایط قبل/بعد، هزینه قطعه و زمان تعمیر سنجیده شود؛ شمار دستورکار بسته‌شده اثبات کاهش خرابی نیست.', 'Assess impact with comparable before/after downtime, parts costs and repair time; closed-order counts do not prove fewer failures.', 'قِس الأثر بتوقف متقارن قبل وبعد وتكلفة القطع وزمن الإصلاح؛ عدد الأوامر المغلقة لا يثبت انخفاض الأعطال.', 'Etkiyi eşdeğer önce/sonra duruş, parça maliyeti ve onarım süresiyle ölçün; kapanan iş sayısı arıza azalmasını kanıtlamaz.'),
    actions: [action('maintenance', w('دستورکار', 'Work orders', 'أوامر العمل', 'İş emirleri')), action('asset', w('شناسنامه تجهیزات', 'Asset register', 'سجل المعدات', 'Ekipman kartları')), action('lab:pdm', w('تحلیل ارتعاش', 'Vibration analysis', 'تحليل الاهتزاز', 'Titreşim analizi'))],
  },
  {
    id: 'energy',
    title: w('انرژی و ارزش اقتصادی اقدام', 'Energy and economic value', 'الطاقة والقيمة الاقتصادية', 'Enerji ve ekonomik değer'),
    summary: w('مصرف ویژه، خط مبنای هم‌شرایط و بازگشت سرمایه نقدی.', 'Specific consumption, comparable baselines and cash-based payback.', 'الاستهلاك النوعي وخط الأساس المتقارن والاسترداد النقدي.', 'Özgül tüketim, eşdeğer referans ve nakit geri ödeme.'),
    purpose: w('قرائت ابتدا/انتها و تناژ هم‌دوره، مصرف را از حجم تولید جدا می‌کند و برای بررسی نشتی و بی‌باری مفید است. برق، گاز و هوای فشرده با واحد جدا ثبت می‌شوند؛ kWh و m³ را مستقیم جمع نکنید.', 'Start/end readings with same-period tonnage separate consumption from output and help investigate leaks/idle use. Electricity, gas and compressed air keep separate units; do not add kWh directly to m³.', 'تفصل القراءات مع إنتاج الفترة الاستهلاك عن الحجم وتساعد على فحص التسرب والعمل دون حمل. تُسجّل الكهرباء والغاز والهواء بوحدات منفصلة؛ لا تجمع kWh مع m³ مباشرة.', 'Başlangıç/bitiş ve aynı dönem tonajı tüketimi hacimden ayırarak kaçak/boşta tüketimi inceletir. Elektrik, gaz ve hava ayrı birimlidir; kWh ile m³ doğrudan toplanmaz.'),
    steps: [
      w('کنتور، خط، تاریخ و حامل را مشخص کنید؛ انتها کمتر از ابتدا نباشد. ریست یا تعویض کنتور را شرح دهید و دوره را جدا کنید.', 'Identify meter, line, date and carrier; end must not be below start. Describe resets/replacements and separate periods.', 'حدّد الكنتور والخط والتاريخ والحامل؛ لا تقل النهاية عن البداية. صف إعادة الضبط أو الاستبدال وافصل الفترات.', 'Sayaç, hat, tarih ve türü belirleyin; bitiş başlangıçtan düşük olmasın. Sıfırlama/değişimi açıklayıp dönemleri ayırın.'),
      w('تناژ واقعی و زمان محدودیت همان دوره را وارد و ارسال کنید؛ خط مبنا از محصول، بار و ساعت مشابه انتخاب شود.', 'Enter actual tonnage/restriction time and submit; choose a baseline with comparable product, load and operating hours.', 'أدخل الإنتاج الفعلي وزمن التقييد وأرسل؛ اختر أساساً بمنتج وحمل وساعات متقاربة.', 'Gerçek tonaj/kısıtlama süresini girip gönderin; benzer ürün, yük ve çalışma saatli referans seçin.'),
      w('تعرفه و خط مبنا را در ابزار انرژی بدهید؛ در ROI منفعت ضایعات، توقف و انرژی را جدا و هزینه بهره‌برداری و ضریب تحقق را اعمال کنید.', 'Enter tariff/baseline in Energy; in ROI, separate scrap, stop and energy benefits and apply OPEX and realization factor.', 'أدخل التعرفة والأساس في الطاقة؛ وافصل في ROI منافع الهالك والتوقف والطاقة وطبّق التشغيل ونسبة التحقق.', 'Enerjiye tarife/referans girin; ROI’de hurda, duruş ve enerji faydasını ayırıp OPEX ve gerçekleşme oranı uygulayın.'),
    ],
    formula: 'consumption = end − start · intensity = kWh / t · net annual benefit = realized gross benefit − annual OPEX · payback(months) = CAPEX / net annual benefit × 12',
    method: w('تناژ صفر شدت تعریف‌نشده دارد. ابزار انرژی فعلی برق را تحلیل می‌کند. زمان آزادشده کارکنان در ROI از منفعت نقدی جداست؛ بازگشت فقط با منفعت خالص مثبت تعریف می‌شود.', 'Zero tonnage gives undefined intensity. The current tool analyzes electricity. ROI separates released staff time from cash benefits; payback requires positive net benefit.', 'عند إنتاج صفري لا تُعرّف الكثافة. تحلل الأداة الكهرباء حالياً. يفصل ROI وقت العاملين عن النقد؛ ويستلزم الاسترداد منفعة صافية موجبة.', 'Sıfır tonajda yoğunluk tanımsızdır. Araç şu anda elektriği analiz eder. ROI boşalan zamanı nakit faydadan ayırır; geri ödeme pozitif net fayda ister.'),
    decision: w('مصرف کل کمتر با تولید کمتر لزوماً صرفه‌جویی نیست. سناریوی کم‌تحقق را بسنجید و یک ضایعه یا توقف را دوبار منفعت نگیرید.', 'Lower use with lower output is not necessarily savings. Assess low-realization scenarios and do not count a scrap/stop benefit twice.', 'الاستهلاك الأقل مع إنتاج أقل ليس وفراً بالضرورة. اختبر سيناريو منخفض التحقق ولا تحسب منفعة الهالك أو التوقف مرتين.', 'Düşük üretimle az tüketim mutlaka tasarruf değildir. Düşük gerçekleşme senaryosunu inceleyin; hurda/duruş faydasını iki kez saymayın.'),
    evidence: w('ارزش قابل دفاع به قرائت، تناژ، تعرفه، هزینه واقعی و دوره مقایسه نیاز دارد. خروجی ابزار سناریو است؛ منفعت محقق‌شده پس از مشاهده و تأیید مالی ثبت شود.', 'Defensible value needs readings, tonnage, tariff, actual costs and a comparison period. Tool output is a scenario; achieved benefit needs observation and financial verification.', 'تحتاج القيمة إلى قراءات وإنتاج وتعرفة وتكاليف وفترة مقارنة. المخرج سيناريو؛ المنفعة المحققة تحتاج مشاهدة وتحققاً مالياً.', 'Savunulabilir değer sayaç, tonaj, tarife, gerçek maliyet ve karşılaştırma ister. Çıktı senaryodur; gerçekleşen fayda gözlem ve mali doğrulama ister.'),
    actions: [action('energy', w('قرائت انرژی', 'Energy readings', 'قراءات الطاقة', 'Enerji okumaları')), action('lab:energy', w('تحلیل مصرف', 'Consumption analysis', 'تحليل الاستهلاك', 'Tüketim analizi')), action('lab:roi', w('تحلیل اقتصادی', 'Economic analysis', 'التحليل الاقتصادي', 'Ekonomik analiz'))],
  },
  {
    id: 'engineering',
    title: w('مهندسی محصول، نسخه ساخت و مواد', 'Product engineering, recipes and materials', 'هندسة المنتج وإصدارات التصنيع والمواد', 'Ürün mühendisliği, reçete ve malzeme'),
    summary: w('کنترل بازنگری، محاسبه فنر و تطبیق مواد با حدود قرارداد.', 'Revision control, spring calculations and contractual material limits.', 'ضبط الإصدارات وحساب النابض وحدود المواد التعاقدية.', 'Revizyon, yay hesabı ve sözleşme malzeme sınırları.'),
    purpose: w('نسخه ساخت هندسه، گرید، قطعه، بازنگری و مرجع پذیرش را یکپارچه ثبت می‌کند. مهندسی و دوقلوی پارامتری حساسیت هندسه و فاصله تا تماس حلقه را بررسی می‌کنند؛ نسخه برای تولید نیازمند تأیید شخص دوم مجاز است.', 'Recipes unify geometry, grade, part, revision and acceptance reference. Engineering/twin tools explore geometry sensitivity and coil clearance; production release needs an authorized second-person approval.', 'تجمع نسخة التصنيع الهندسة والدرجة والقطعة والإصدار ومرجع القبول. تفحص الهندسة والتوأم الحساسية والمسافة إلى تماس اللفات؛ ويتطلب الإنتاج اعتماد شخص ثانٍ مخوّل.', 'Reçete geometri, sınıf, parça, revizyon ve kabul kaynağını birleştirir. Mühendislik/ikiz geometri hassasiyeti ve sarım açıklığını inceler; üretim için yetkili ikinci onay gerekir.'),
    steps: [
      w('از نقشه، کد، بازنگری، گرید، قطر مفتول/میانگین، حلقه فعال و طول آزاد را بگیرید؛ مرجع پذیرش و محدودیت فرآیند را بنویسید.', 'Take code, revision, grade, wire/mean diameter, active coils and free length from the drawing; record acceptance reference/process limits.', 'خذ الرمز والإصدار والدرجة والأقطار واللفات الفعالة والطول الحر من الرسم، وسجّل مرجع القبول وحدود العملية.', 'Kod, revizyon, sınıf, tel/ortalama çap, aktif sarım ve serbest boyu çizimden alın; kabul/süreç sınırlarını yazın.'),
      w('در فنر فشاری گرد هندسه، حلقه کل و بار را وارد و نرخ، تنش Wahl و ارتفاع جامد را کنترل کنید؛ رابطه خطی را پس از تماس حلقه ادامه ندهید.', 'For a round-wire compression spring, enter geometry, total coils and load; check rate, Wahl stress and solid height. Do not extend linear behavior beyond contact.', 'للنابض الضاغط الدائري أدخل الهندسة واللفات الكلية والحمل وراجع الثابت وإجهاد Wahl والارتفاع الصلب؛ لا تمد الخطية بعد التماس.', 'Yuvarlak telli basma yayında geometri, toplam sarım ve yükü girip sabit, Wahl gerilmesi ve blok boyunu kontrol edin; temastan sonra doğrusallığı sürdürmeyin.'),
      w('عناصر و HRC را با حدود گواهی/قرارداد در متالورژی بسنجید؛ شماره ذوب را حفظ و نسخه را برای تأیید کیفیت یا مدیر کارخانه ارسال کنید.', 'Check elements/HRC against certificate/contract limits in metallurgy; retain heat ID and submit the recipe for quality or factory-manager approval.', 'افحص العناصر وHRC بحدود الشهادة أو العقد، واحفظ رقم الصهرة وأرسل النسخة لاعتماد الجودة أو المدير.', 'Element/HRC’yi sertifika/sözleşmeyle kontrol edin; döküm kimliğini koruyup reçeteyi kalite veya müdür onayına gönderin.'),
    ],
    formula: 'k = Gd⁴ / (8D³n) · C = D / d · Kw = (4C − 1) / (4C − 4) + 0.615 / C · τ = Kw × 8FD / (πd³)',
    method: w('ابزار فعلی G=۷۸۵۰۰ MPa و واحدهای mm/N/MPa را فرض می‌کند. تغییر ماده، خستگی، کمانش و تنش باقیمانده مدل و آزمون جدا می‌خواهد.', 'The current tool assumes G=78,500 MPa and mm/N/MPa units. Material changes, fatigue, buckling and residual stress need separate models/tests.', 'تفترض الأداة G=٧٨٥٠٠ MPa ووحدات mm/N/MPa. تغيّر المادة والتعب والانبعاج والإجهاد المتبقي تحتاج نماذج واختبارات منفصلة.', 'Araç G=78.500 MPa ve mm/N/MPa varsayar. Malzeme değişimi, yorulma, burkulma ve artık gerilme ayrı model/test ister.'),
    decision: w('محاسبه برای بررسی طراحی است؛ صدور نقشه و پذیرش صنعتی به مسئول مهندسی و آزمون وابسته است. تطبیق چند عنصر و سختی گواهی کامل گرید یا اثبات خستگی نیست.', 'Calculations support design review; drawing release/industrial acceptance need engineering ownership and tests. Selected chemistry/hardness checks do not certify a full grade or fatigue life.', 'الحساب لمراجعة التصميم؛ الإصدار والقبول يحتاجان مسؤول الهندسة والاختبار. مطابقة عناصر وصلادة لا تمنح شهادة كاملة ولا تثبت التعب.', 'Hesap tasarım incelemesidir; yayımlama/kabul mühendislik ve test ister. Seçilmiş kimya/sertlik kontrolü tam sınıf veya yorulma sertifikası değildir.'),
    evidence: w('خروجی: نسخه تأییدشده، نقشه، ماده/ذوب و بررسی پارامتری. دلیل بازنگری را ثبت کنید تا تولید، کیفیت و مهندسی یک نسخه مشترک داشته باشند.', 'Output: approved recipe, drawing, material/heat and parametric review. Record revision reasons so production, quality and engineering share a version.', 'المخرج: نسخة معتمدة ورسم ومادة/صهرة ومراجعة بارامترية. سجّل سبب التعديل لتستخدم الفرق نسخة واحدة.', 'Çıktı: onaylı reçete, çizim, malzeme/döküm ve parametrik inceleme. Ekiplerin aynı sürümü kullanması için değişiklik nedenini yazın.'),
    actions: [action('recipe', w('نسخه ساخت', 'Recipe revisions', 'إصدارات التصنيع', 'Reçete revizyonları')), action('lab:engineering', w('محاسبه مهندسی', 'Engineering calculation', 'الحساب الهندسي', 'Mühendislik hesabı')), action('lab:metallurgy', w('کنترل مواد', 'Material checks', 'فحص المواد', 'Malzeme kontrolü'))],
  },
  {
    id: 'laboratory',
    title: w('روش‌های آزمایشگاه و تحلیل', 'Laboratory and analysis methods', 'طرق المختبر والتحليل', 'Laboratuvar ve analiz yöntemleri'),
    summary: w('انتخاب ۱۳ ابزار بر اساس پرسش، ورودی و اقدام بعدی.', 'Choose among 13 tools by question, input and next action.', 'اختيار الأدوات الثلاث عشرة حسب السؤال والمدخل والخطوة التالية.', 'Soru, girdi ve sonraki adıma göre 13 araç seçimi.'),
    purpose: w('آزمایشگاه پاسخ می‌دهد چه متغیری اثر دارد، نتیجه با چه واحد و فرضی به دست می‌آید و بعد چه اقدامی لازم است. ابزار را از جدول برگزینید و ورودی از شرایط واقعی همسان یا سناریوی مشخص بدهید.', 'The laboratory shows which variable matters, which units/assumptions produce the result and what action follows. Select a tool and enter matching real conditions or a defined scenario.', 'يبيّن المختبر المتغيّر المؤثر ووحدات وافتراضات النتيجة والإجراء التالي. اختر الأداة وأدخل ظروفاً فعلية متطابقة أو سيناريو محدداً.', 'Laboratuvar etkili değişkeni, sonuç birimi/varsayımını ve sonraki işlemi gösterir. Aracı seçip eşdeğer gerçek koşul veya tanımlı senaryo girin.'),
    steps: [
      w('پرسش و معیار تصمیم را قبل از محاسبه بنویسید؛ مثال: اندازه با عدم قطعیت داخل تلرانس است؟ کدام مؤلفه OEE افت کرده؟', 'Define the question/criterion first: is the dimension within tolerance including uncertainty? Which OEE component fell?', 'حدّد السؤال والمعيار أولاً: هل البعد داخل التفاوت مع عدم اليقين؟ أي مكوّن OEE انخفض؟', 'Önce soru/ölçütü yazın: belirsizlikle boyut toleransta mı? Hangi OEE bileşeni düştü?'),
      w('واحد، ترتیب زمان، شمار نمونه و حدود ورودی را کنترل کنید؛ برای حساسیت یک متغیر را تغییر دهید، نه داده را برای نتیجه دلخواه.', 'Check units, time order, sample counts and limits; change one variable for sensitivity, not data to force a desired result.', 'راجع الوحدات والزمن والعينة والحدود؛ غيّر متغيّراً للحساسية ولا تغيّر البيانات لفرض نتيجة.', 'Birim, sıra, örnek ve sınırı kontrol edin; hassasiyet için tek değişkeni değiştirin, istenen sonuç için veriyi değil.'),
      w('نتیجه و فرض‌ها را در رکورد حوزه مربوط ثبت کنید؛ محاسبه به‌تنهایی رکورد تولید یا تأیید کیفیت نمی‌سازد و گردش بررسی مستقل جداست.', 'Record results/assumptions in the relevant domain; calculation alone creates no production record or quality approval, and independent review remains separate.', 'سجّل النتيجة والافتراضات في المجال؛ الحساب وحده لا ينشئ إنتاجاً أو اعتماد جودة وتبقى المراجعة المستقلة منفصلة.', 'Sonuç/varsayımı ilgili alana yazın; hesap tek başına üretim kaydı veya kalite onayı oluşturmaz, bağımsız inceleme ayrıdır.'),
    ],
    method: w('بینایی ماتریس TP/FN/FP/TN را ارزیابی و پروفایل با mm/px اندازه را محاسبه می‌کند. دوربین با اجازه صریح تصویر زنده و PNG محلی می‌دهد؛ تشخیص تصویر یا اندازه‌گیری خودکار کالیبره از این‌ها نتیجه نمی‌شود.', 'Vision evaluates TP/FN/FP/TN; profile calculates dimensions with mm/px. Explicitly authorized camera use provides live video/local PNG, not automatic image detection or calibrated metrology.', 'تقيّم الرؤية TP/FN/FP/TN ويحسب المقطع بُعداً بـmm/px. توفّر الكاميرا بإذن صريح فيديو وPNG محلياً، لا كشفاً آلياً أو قياساً معايراً.', 'Görsel değerlendirme TP/FN/FP/TN’yi, profil mm/px ile boyutu hesaplar. Açık izinli kamera canlı video/yerel PNG sağlar; otomatik algılama veya kalibre ölçüm değil.'),
    decision: w('حدود پذیرش از قرارداد تعیین شوند؛ Cpk=۱٫۳۳ یا OEE=۷۰٪ نشانه تحلیلی‌اند، نه استاندارد همه محصولات. SCADA فقط ظرفیت را برآورد می‌کند و اتصال PLC یا فرمان صنعتی ندارد.', 'Set acceptance limits from contracts; Cpk=1.33 or OEE=70% are analytical cues, not universal standards. SCADA estimates capacity only, without PLC connection/commands.', 'حدّد القبول من العقد؛ Cpk=١٫٣٣ أو OEE=٧٠٪ مؤشرات تحليل لا معايير عامة. يقدّر SCADA السعة فقط بلا ربط PLC أو أوامر.', 'Kabulü sözleşmeden belirleyin; Cpk=1,33 veya OEE=%70 evrensel değil analitik ipucudur. SCADA yalnız kapasite tahmini yapar; PLC bağlantısı/komutu yoktur.'),
    evidence: w('برای بازتولید، ورودی، واحد، فرض، نسخه روش و نتیجه را نگه دارید. در استفاده دوربین، تصویر در مرورگر/دانلود محلی می‌ماند؛ جریان با توقف یا خروج قطع می‌شود.', 'Retain input, unit, assumptions, method version and result for reproduction. Camera images remain in the browser/local download; stop or exit ends the stream.', 'احتفظ بالمدخل والوحدة والافتراضات وإصدار الطريقة والنتيجة. تبقى الصور في المتصفح والتنزيل المحلي ويتوقف البث بالإيقاف أو الخروج.', 'Tekrar için girdi, birim, varsayım, yöntem sürümü ve sonucu saklayın. Görüntü tarayıcı/yerel indirmede kalır; durdurma veya çıkış akışı kapatır.'),
    actions: [action('lab:twin', w('بازکردن آزمایشگاه', 'Open laboratory', 'فتح المختبر', 'Laboratuvarı aç'))],
  },
  {
    id: 'model',
    title: w('مدل داده و مسیر پذیرش صنعتی', 'Data model and industrial acceptance', 'نموذج البيانات والقبول الصناعي', 'Veri modeli ve endüstriyel kabul'),
    summary: w('شناسنامه آموزش واقعی، معنی معیارها و انتقال کنترل‌شده به خط.', 'Actual training provenance, metrics and controlled line transfer.', 'مصدر التدريب الفعلي والمقاييس والانتقال المنضبط للخط.', 'Gerçek eğitim kaynağı, metrikler ve kontrollü hat geçişi.'),
    purpose: w('مدل واقعی روی UCI Steel Plates Faults عمومی با ۱۹۴۱ ردیف، ۲۷ ویژگی عددی و ۷ کلاس آموزش یافته است. رگرسیون لجستیک چندکلاسه از ۱۵۵۳ ردیف آموزش و ۳۸۸ آزمون جدا استفاده کرده؛ این مدل عیب ورق فولادی است، نه تصویر فنر یا مدل زبانی اختصاصی.', 'The actual model uses public UCI Steel Plates Faults: 1,941 rows, 27 numeric features and 7 classes. Multinomial logistic regression used 1,553 training and 388 separate test rows. This is steel-plate fault modeling, not spring images or a proprietary language model.', 'يستخدم النموذج الفعلي UCI Steel Plates Faults العامة: ١٩٤١ صفاً و٢٧ سمة و٧ فئات. استُخدم انحدار لوجستي متعدد الفئات مع ١٥٥٣ تدريباً و٣٨٨ اختباراً منفصلاً. النموذج لعيوب الصفائح لا صور النوابض أو لغة خاصة.', 'Gerçek model açık UCI Steel Plates Faults kullanır: 1.941 satır, 27 sayısal özellik ve 7 sınıf. Çok sınıflı lojistik regresyon 1.553 eğitim/388 ayrı test kullanmıştır. Çelik levha kusur modelidir; yay görüntüsü veya özel dil modeli değildir.'),
    steps: [
      w('شناسنامه و نمونه ویژگی را باز کنید؛ عددها را با ترتیب و واحد مورد انتظار بدهید. احتمال کلاس، اندازه‌گیری فیزیکی یا گواهی کیفیت نیست.', 'Open the registry/feature example; enter numbers in the expected order/units. Class probability is not physical measurement or certification.', 'افتح السجل ومثال السمات وأدخل الأرقام بالترتيب والوحدة المطلوبة. احتمال الفئة ليس قياساً أو شهادة.', 'Sicil/özellik örneğini açın; beklenen sıra/birimde sayıları girin. Sınıf olasılığı fiziksel ölçüm veya sertifika değildir.'),
      w('برای خط، قطعه، عیب بحرانی، دوربین/نور، روش برچسب و مسئول کیفیت تعریف شود؛ داده مجاز با تقسیم مستقل بچ/زمان آماده شود و آزمون به آموزش نشت نکند.', 'For the line, define part, critical defects, camera/light, labels and quality owner; prepare authorized data with independent batch/time splits and no test leakage.', 'للخط حدّد القطعة والعيب الحرج والكاميرا والضوء والوسم ومسؤول الجودة، مع بيانات مصرّح بها وتقسيم دفعة/زمن مستقل بلا تسرّب اختبار.', 'Hat için parça, kritik kusur, kamera/ışık, etiket ve kalite sorumlusu tanımlayın; izinli veriyi bağımsız parti/zaman ayrımıyla test sızıntısı olmadan hazırlayın.'),
      w('مدل مخصوص خط ابتدا مشاهده موازی شود؛ عیب ازدست‌رفته، رد اشتباه، تأخیر و پایداری شیفت سنجیده و با نمونه مستقل و تأیید مسئول کارخانه پذیرفته شود.', 'Evaluate a line-specific model in shadow mode; measure missed defects, false rejects, latency and shift stability; accept with independent samples and factory sign-off.', 'قيّم نموذج الخط بالمراقبة الموازية، وقِس الفائت والرفض الخاطئ والتأخير واستقرار الوردية، ثم اقبل بعينة مستقلة وتوقيع المصنع.', 'Hat modelini paralel gözlemde değerlendirin; kaçan kusur, yanlış ret, gecikme ve vardiya kararlılığını ölçün; bağımsız örnek ve fabrika onayıyla kabul edin.'),
    ],
    formula: 'precision = TP / (TP + FP) · recall = TP / (TP + FN) · missed rate = FN / (TP + FN) · F1 = 2PR / (P + R)',
    method: w('آزمون مرجع: دقت ۷۰٫۳۶٪، دقت متوازن ۶۷٫۹۳٪، Macro-F1=۰٫۶۸۶. تقسیم طبقه‌بندی‌شده با گروه ویژگی و مقیاس‌ساز فقط روی آموزش اجرا شده؛ معیار هر کلاس و تعداد نمونه را کنار میانگین بخوانید.', 'Reference test: accuracy 70.36%, balanced accuracy 67.93%, Macro-F1=0.686. Stratified feature-group splitting and training-only scaling were used; read class metrics/sample counts with averages.', 'الاختبار: دقة ٧٠٫٣٦٪ ومتوازنة ٦٧٫٩٣٪ وMacro-F1=٠٫٦٨٦. استُخدم تقسيم طبقي بمجموعات السمات ومعايرة التدريب فقط؛ اقرأ مقاييس الفئة وعددها مع المتوسط.', 'Referans: doğruluk %70,36, dengeli %67,93, Macro-F1=0,686. Özellik gruplu tabakalı ayrım ve yalnız eğitim ölçeklemesi kullanıldı; sınıf metrik/adetlerini ortalamayla okuyun.'),
    decision: w('دقت عمومی مجوز پذیرش یا رد قطعه نیست. برای عیب ایمنی، FN و حد بالای اطمینان مهم است. شناسنامه و استنتاج مرجع قابل استفاده‌اند؛ آموزش کارخانه و اتصال بینایی صنعتی پذیرش جدا دارند.', 'Public accuracy does not authorize part acceptance/rejection. Safety defects need FN and confidence upper bounds. Registry/reference inference are usable; factory training/industrial vision need separate acceptance.', 'الدقة العامة لا تجيز قبول القطعة أو رفضها. تحتاج عيوب السلامة FN وحد الثقة الأعلى. السجل والاستدلال متاحان؛ تدريب المصنع والرؤية الصناعية يحتاجان قبولاً منفصلاً.', 'Açık doğruluk parça kabul/ret yetkisi vermez. Güvenlik kusuru FN ve güven üst sınırı ister. Sicil/referans çıkarım kullanılabilir; fabrika eğitimi/endüstriyel görüntü ayrı kabul ister.'),
    evidence: w('شناسنامه منشأ، مجوز CC BY 4.0، هش داده، تقسیم و آزمون را دارد. برای نسخه صنعتی، هش مدل، نسخه برچسب، معیار پذیرش و شاهد مشاهده موازی نیز حفظ شود.', 'The registry holds provenance, CC BY 4.0, data hash, split and test. Industrial releases also need model hash, label version, acceptance criteria and shadow evidence.', 'يحفظ السجل المصدر وترخيص CC BY 4.0 والبصمة والتقسيم والاختبار. تحتاج النسخة الصناعية بصمة النموذج وإصدار الوسم والقبول ودليل المراقبة.', 'Sicil kaynak, CC BY 4.0, veri özeti, ayrım ve testi tutar. Endüstriyel sürüm model özeti, etiket sürümü, kabul ölçütü ve paralel gözlem kanıtı da ister.'),
    actions: [action('models', w('شناسنامه و استنتاج', 'Registry and inference', 'السجل والاستدلال', 'Sicil ve çıkarım')), action('lab:vision', w('ارزیابی تشخیص', 'Detection evaluation', 'تقييم الكشف', 'Algılama değerlendirmesi'))],
  },
  {
    id: 'governance',
    title: w('مدیریت، ممیزی و تداوم خدمت', 'Management, audit and service continuity', 'الإدارة والتدقيق واستمرارية الخدمة', 'Yönetim, denetim ve hizmet sürekliliği'),
    summary: w('پایش سامانه و دسترسی، بررسی شواهد و رویه قطع/بازیابی.', 'System/access monitoring, evidence and interruption/recovery procedures.', 'مراقبة النظام والصلاحيات والأدلة وإجراءات الانقطاع والاستعادة.', 'Sistem/erişim izleme, kanıt ve kesinti/kurtarma prosedürleri.'),
    purpose: w('مدیر کارخانه تصمیم عملیاتی و تأیید مجاز را بر عهده دارد؛ مدیر سامانه حساب، نشست، سلامت و رخداد فنی را مدیریت می‌کند؛ ناظر سوابق را می‌خواند. مسئولیت صنعتی و اداره زیرساخت روشن و جدا هستند.', 'The factory manager owns operational decisions/permitted approvals; the administrator manages accounts, sessions, health and technical events; the auditor reads records. Industrial decisions and infrastructure administration have distinct responsibilities.', 'يتولى مدير المصنع القرار والاعتماد المسموح، ومدير النظام الحساب والجلسات والصحة والأحداث، ويقرأ المراقب السجلات. مسؤولية الصناعة والبنية التحتية منفصلتان.', 'Müdür operasyonel karar/izinli onayı; yönetici hesap, oturum, sağlık ve olayı yönetir; denetçi kayıtları okur. Endüstriyel karar ve altyapı sorumluluğu ayrıdır.'),
    steps: [
      w('مدیر سامانه دوره‌ای نقش، حساب و نشست فعال را مرور کند؛ حساب شخصی و دسترسی متناسب وظیفه باشد، نه حساب مشترک روزمره.', 'Periodically review roles, accounts and active sessions; use personal accounts and duty-matched access, not shared daily accounts.', 'راجع الأدوار والحسابات والجلسات دورياً، واستخدم حسابات شخصية وصلاحيات حسب المهمة لا حسابات مشتركة.', 'Rol, hesap ve oturumu düzenli inceleyin; ortak günlük hesap değil kişisel ve göreve uygun erişim kullanın.'),
      w('سلامت DB، نسخه کد و رخداد را در پایش بررسی کنید؛ در خطا شناسه، زمان، نقش و پیام را نگه دارید، نه رمز و اطلاعات محرمانه.', 'Check DB health, code version and events in monitoring; retain error IDs, time, role and message, not passwords/confidential information.', 'افحص صحة DB والإصدار والأحداث، واحفظ معرّف الخطأ ووقته ودوره ورسالة دون كلمات مرور أو سرية.', 'İzlemede DB, sürüm ve olayı kontrol edin; hatanın kimlik, zaman, rol ve mesajını saklayın, parola/gizli veriyi değil.'),
      w('در قطعی طبق رویه کارخانه ثبت موقت با زمان/شناسه انجام شود؛ بعد اتصال تطبیق و فقط موارد ثبت‌نشده وارد شود. بازیابی با مسئول زیرساخت و آزمون سلامت است.', 'During outages, use factory temporary records with time/IDs; reconcile after reconnection and enter missing items only. Infrastructure staff perform recovery and health checks.', 'في الانقطاع اتبع التسجيل المؤقت بوقت ومعرّف، ثم طابق بعد الاتصال وأدخل المفقود فقط. ينفّذ مسؤول البنية الاستعادة وفحص الصحة.', 'Kesintide zaman/kimlikli geçici kayıt kullanın; bağlantı sonrası karşılaştırıp yalnız eksikleri girin. Altyapı sorumlusu kurtarma ve sağlık kontrolü yapar.'),
    ],
    method: w('نسخه با SHA و validate/deploy/health شناخته می‌شود. dist در Nginx و API اختصاصی Node/SQLite روی Unix socket سرو می‌شود، بدون TCP تازه. پیش از استقرار پشتیبان DB گرفته می‌شود.', 'SHA and validate/deploy/health identify releases. Nginx serves dist; dedicated Node/SQLite API uses a Unix socket without a new TCP port. DB backups precede deployment.', 'يحدد SHA وvalidate/deploy/health الإصدار. يخدم Nginx ملف dist وتستخدم API الخاصة Node/SQLite مقبس Unix بلا TCP جديد. يُنسخ DB قبل النشر.', 'Sürüm SHA ve validate/deploy/health ile tanımlanır. Nginx dist sunar; özel Node/SQLite API yeni TCP olmadan Unix soketi kullanır. Dağıtımdan önce DB yedeklenir.'),
    decision: w('پشتیبان داشتن اثبات بازیابی موفق نیست؛ آزمون و زمان هدف در رویه ثبت شود. قطعی یا داده ناقص را صفر عملکرد نکنید، دوره را با علت جدا گزارش کنید.', 'A backup does not prove recovery; document restore tests/targets. Do not treat outages/missing data as zero performance; report the period separately with a reason.', 'النسخة الاحتياطية لا تثبت الاستعادة؛ وثّق الاختبار والهدف. لا تعتبر الانقطاع أو النقص أداءً صفرياً، بل أبلغ عن الفترة بسببها.', 'Yedek kurtarmayı kanıtlamaz; test/hedefi belgeleyin. Kesinti/eksik veriyi sıfır performans saymayın; dönemi nedeniyle ayrı raporlayın.'),
    evidence: w('بسته ممیزی: نسخه، گیت، رکورد تأییدشده، رخداد دسترسی و شاهد پشتیبان. نرم‌افزار عملیاتی، اتصال صنعتی و منفعت میدانی هر کدام شاهد مستقل دارند.', 'Audit package: version, gates, approved records, access events and backup evidence. Operational software, industrial integration and field benefit each need their own evidence.', 'حزمة التدقيق: الإصدار والبوابات والسجلات المعتمدة والوصول والنسخ. للبرمجيات والربط والمنفعة الميدانية دليل مستقل لكل منها.', 'Denetim paketi: sürüm, kontroller, onaylı kayıt, erişim ve yedek kanıtı. Yazılım, endüstriyel entegrasyon ve saha faydası ayrı kanıt ister.'),
    actions: [action('system', w('پایش مدیر سامانه', 'Administrator monitoring', 'مراقبة المدير', 'Yönetici izleme')), action('settings', w('تنظیمات شخصی', 'Personal settings', 'التفضيلات الشخصية', 'Kişisel ayarlar'))],
  },
];

const roles = [
  {id: 'admin', name: w('مدیر سامانه', 'System administrator', 'مدير النظام', 'Sistem yöneticisi'), task: w('حساب، نقش، نشست و سلامت/لاگ‌ها را مدیریت کنید؛ تأیید رکورد خود ممنوع است. دسترسی حوزه را از مجوز سرور بخوانید.', 'Manage accounts, roles, sessions and health/logs; self-approval is forbidden. Read domain access from server permissions.', 'أدِر الحسابات والأدوار والجلسات والصحة والسجلات؛ اعتماد سجلك ممنوع. تؤخذ صلاحيات المجال من الخادم.', 'Hesap, rol, oturum ve sağlık/günlükleri yönetin; kendi kaydınızı onaylayamazsınız. Alan erişimi sunucu iznidir.'), keys: ['system', 'activity']},
  {id: 'executive', name: w('مدیر کارخانه', 'Factory manager', 'مدير المصنع', 'Fabrika müdürü'), task: w('صف بررسی را مرور، رکورد دیگران را تأیید/رد و افت تولید، انرژی و ریسک را به اقدام مسئول‌دار تبدیل کنید.', 'Review queues, approve/reject others’ records and turn production/energy losses and risks into owned actions.', 'راجع القوائم واعتمد أو ارفض سجلات الآخرين وحوّل الخسائر والمخاطر إلى إجراءات بمسؤول.', 'Kuyruğu inceleyip başkasının kaydını onaylayın/reddedin; üretim/enerji kaybını ve riski sorumlu eyleme çevirin.'), keys: ['production', 'energy']},
  {id: 'production', name: w('مسئول تولید', 'Production officer', 'مسؤول الإنتاج', 'Üretim sorumlusu'), task: w('شیفت، مواد/قطعات، درخواست تعمیر و NCR ثبت کنید؛ زمان و شمارش را تطبیق و ارسال کنید.', 'Record shifts, materials/spares, maintenance requests and NCRs; reconcile times/counts and submit.', 'سجّل الورديات والمواد والقطع وطلبات الإصلاح وNCR؛ وطابق الأوقات والأعداد ثم أرسل.', 'Vardiya, malzeme/parça, bakım isteği ve NCR kaydedin; süre/adetleri karşılaştırıp gönderin.'), keys: ['production', 'inventory']},
  {id: 'quality', name: w('کنترل کیفیت', 'Quality control', 'مراقبة الجودة', 'Kalite kontrol'), task: w('بازرسی، کالیبراسیون و NCR ثبت کنید؛ بازرسی، نسخه ساخت و اقدام اصلاحی شخص دیگر را در مجوز خود بررسی کنید.', 'Record inspection, calibration and NCRs; review others’ inspection, recipes and corrections within your permissions.', 'سجّل التفتيش والمعايرة وNCR وراجع عمل الآخرين والتصنيع والتصحيح ضمن صلاحياتك.', 'Muayene, kalibrasyon ve NCR kaydedin; başkasının muayene/reçete/düzeltmesini izinlerinizle inceleyin.'), keys: ['inspection', 'calibration']},
  {id: 'maintenance', name: w('نگهداری و تعمیرات', 'Maintenance', 'الصيانة', 'Bakım'), task: w('تجهیز، دستورکار و قطعه ثبت کنید؛ دستورکار شخص دیگر را بررسی و توقف/رفع عیب واقعی را نگه دارید.', 'Record assets, work orders and spares; review others’ orders and retain actual downtime/resolution.', 'سجّل المعدات والأوامر والقطع وراجع أوامر الآخرين واحفظ التوقف والحل الفعلي.', 'Ekipman, iş emri ve parça kaydedin; başkasının emrini inceleyip gerçek duruş/çözümü tutun.'), keys: ['maintenance', 'asset']},
  {id: 'energy', name: w('کارشناس انرژی', 'Energy specialist', 'اختصاصي الطاقة', 'Enerji uzmanı'), task: w('قرائت، حامل، تناژ و محدودیت ثبت کنید؛ شدت مصرف را تحلیل و برای تأیید مدیر کارخانه ارسال کنید.', 'Record readings, carrier, tonnage and restrictions; analyze intensity and submit to the factory manager.', 'سجّل القراءات والحامل والإنتاج والقيود وحلّل الكثافة وأرسل لمدير المصنع.', 'Sayaç, tür, tonaj ve kısıt kaydedin; yoğunluğu analiz edip müdür onayına gönderin.'), keys: ['energy', 'lab:energy']},
  {id: 'engineering', name: w('مهندسی و توسعه', 'Engineering and development', 'الهندسة والتطوير', 'Mühendislik ve geliştirme'), task: w('نسخه ساخت، تجهیز و اطلاعات کالیبراسیون آماده کنید؛ مرجع طراحی و ماده را به رکورد قابل بررسی تبدیل کنید.', 'Prepare recipes, assets and calibration data; convert design/material references into reviewable records.', 'أعد التصنيع والمعدات والمعايرة وحوّل مراجع التصميم والمواد إلى سجلات قابلة للمراجعة.', 'Reçete, ekipman ve kalibrasyonu hazırlayın; tasarım/malzeme kaynağını incelenebilir kayda çevirin.'), keys: ['recipe', 'lab:engineering']},
  {id: 'auditor', name: w('ناظر و ارزیاب', 'Auditor and evaluator', 'المراقب والمقيّم', 'Denetçi ve değerlendirici'), task: w('سوابق/خروجی را بخوانید و منشأ و تأیید مستقل را تطبیق دهید؛ این نقش ثبت یا تأیید عملیاتی ندارد.', 'Read records/exports and reconcile provenance/independent approval; this role has no operational write/approval rights.', 'اقرأ السجلات والمخرجات وطابق المصدر والاعتماد المستقل؛ لا يملك الدور تسجيلًا أو اعتماداً تشغيلياً.', 'Kayıt/çıktıyı okuyup kaynak/bağımsız onayı karşılaştırın; bu rol operasyonel kayıt/onay yapamaz.'), keys: ['production', 'inspection']},
];
const tools = [
  ['twin', w('دوقلوی پارامتری', 'Parametric twin', 'التوأم البارامتري', 'Parametrik ikiz'), w('هندسه/بار ← نرخ، تنش و فاصله تماس حلقه؛ سناریوی طراحی.', 'Geometry/load → rate, stress and coil clearance; design scenarios.', 'الهندسة والحمل ← الثابت والإجهاد ومسافة اللفات؛ سيناريو تصميم.', 'Geometri/yük → sabit, gerilme ve sarım açıklığı; tasarım senaryosu.')],
  ['vision', w('ارزیابی بینایی', 'Vision evaluation', 'تقييم الرؤية', 'Görsel değerlendirme'), w('TP/FN/FP/TN ← دقت، precision/recall و حد عیب ازدست‌رفته.', 'TP/FN/FP/TN → accuracy, precision/recall and missed-defect bound.', 'TP/FN/FP/TN ← الدقة وprecision/recall وحد العيب الفائت.', 'TP/FN/FP/TN → doğruluk, kesinlik/duyarlılık ve kaçan kusur sınırı.')],
  ['profile', w('پروفایل ابعادی', 'Dimensional profile', 'المقطع البُعدي', 'Boyutsal profil'), w('مرجع mm/px ← مقیاس و اندازه ± عدم قطعیت؛ تلرانس.', 'Reference mm/px → scale/dimension ± uncertainty; tolerance.', 'مرجع mm/px ← المقياس والبُعد ± عدم اليقين؛ التفاوت.', 'Referans mm/px → ölçek/boyut ± belirsizlik; tolerans.')],
  ['quality', w('کیفیت آماری', 'Statistical quality', 'الجودة الإحصائية', 'İstatistiksel kalite'), w('نمونه/معیوب ← نرخ و بازه Wilson ۹۵٪؛ ریسک نمونه.', 'Samples/defects → rate and 95% Wilson interval; sample risk.', 'العينات والعيوب ← المعدل وفاصل Wilson ٩٥٪؛ خطر العينة.', 'Numune/kusur → oran ve %95 Wilson aralığı; örnek riski.')],
  ['pdm', w('پایش وضعیت', 'Condition monitoring', 'مراقبة الحالة', 'Durum izleme'), w('سرعت mm/s ← AC RMS، ضریب قله و نسبت مبنا؛ اولویت بررسی.', 'Velocity mm/s → AC RMS, crest and baseline ratio; review priority.', 'سرعة mm/s ← AC RMS والقمة ونسبة الأساس؛ أولوية الفحص.', 'mm/s hız → AC RMS, tepe ve referans oranı; inceleme önceliği.')],
  ['oee', w('بهره‌وری OEE', 'OEE productivity', 'إنتاجية OEE', 'OEE verimliliği'), w('زمان/سیکل/شمارش ← A/P/Q و OEE؛ عامل افت.', 'Time/cycle/count → A/P/Q and OEE; loss component.', 'الوقت والدورة والعدد ← A/P/Q وOEE؛ مكوّن الخسارة.', 'Süre/çevrim/adet → A/P/Q ve OEE; kayıp bileşeni.')],
  ['energy', w('شدت انرژی', 'Energy intensity', 'كثافة الطاقة', 'Enerji yoğunluğu'), w('قرائت/تناژ/تعرفه ← kWh/t و هزینه اختلاف مبنا.', 'Readings/tonnage/tariff → kWh/t and baseline cost difference.', 'القراءات والإنتاج والتعرفة ← kWh/t وفرق تكلفة الأساس.', 'Sayaç/tonaj/tarife → kWh/t ve referans maliyet farkı.')],
  ['engineering', w('مهندسی فنر', 'Spring engineering', 'هندسة النابض', 'Yay mühendisliği'), w('فنر گرد ← نرخ، تنش Wahl و ارتفاع جامد؛ پیش از آزمون.', 'Round-wire spring → rate, Wahl stress and solid height; pre-test.', 'نابض دائري ← الثابت وإجهاد Wahl والارتفاع الصلب؛ قبل الاختبار.', 'Yuvarlak yay → sabit, Wahl gerilmesi ve blok boyu; test öncesi.')],
  ['metallurgy', w('کنترل مواد', 'Material checks', 'فحص المواد', 'Malzeme kontrolü'), w('عناصر/HRC و حدود ← حاشیه انطباق؛ بررسی گواهی ذوب.', 'Elements/HRC and limits → compliance margins; heat certificate.', 'العناصر وHRC والحدود ← هوامش المطابقة؛ شهادة الصهرة.', 'Element/HRC ve sınır → uygunluk payı; döküm sertifikası.')],
  ['spc', w('کنترل آماری فرآیند', 'Statistical process control', 'الضبط الإحصائي', 'İstatistiksel süreç kontrolü'), w('اندازه مرتب ← I–MR، Cp/Cpk، Pp/Ppk؛ غربال روند.', 'Ordered measurements → I–MR, Cp/Cpk, Pp/Ppk; trend screening.', 'قياسات مرتبة ← I–MR وCp/Cpk وPp/Ppk؛ فحص الاتجاه.', 'Sıralı ölçüm → I–MR, Cp/Cpk, Pp/Ppk; eğilim tarama.')],
  ['scada', w('ظرفیت SCADA', 'SCADA capacity', 'سعة SCADA', 'SCADA kapasitesi'), w('تگ/نرخ/بایت/سربار ← پهنای باند، حجم روز و بافر؛ برنامه اتصال.', 'Tags/rate/bytes/overhead → bandwidth, daily volume and buffer; planning.', 'الوسوم والمعدل والبايت والحمل ← النطاق والحجم والمخزن؛ التخطيط.', 'Etiket/hız/bayt/ek yük → bant, günlük hacim ve tampon; planlama.')],
  ['roi', w('ارزش اقتصادی', 'Economic value', 'القيمة الاقتصادية', 'Ekonomik değer'), w('ضایعات/توقف/انرژی/هزینه ← منفعت خالص و بازگشت؛ حساسیت.', 'Scrap/stops/energy/cost → net benefit/payback; sensitivity.', 'الهالك والتوقف والطاقة والتكلفة ← صافي واسترداد؛ الحساسية.', 'Hurda/duruş/enerji/maliyet → net fayda/geri ödeme; hassasiyet.')],
  ['camera', w('دوربین زنده', 'Live camera', 'الكاميرا الحية', 'Canlı kamera'), w('اجازه صریح ← تصویر و PNG محلی؛ قطع جریان با خروج.', 'Explicit permission → video/local PNG; stream ends on exit.', 'إذن صريح ← فيديو وPNG محلي؛ يتوقف البث بالخروج.', 'Açık izin → video/yerel PNG; çıkış akışı durdurur.')],
] as const;
const glossary = [
  [w('بچ / شماره ذوب', 'Batch / heat number', 'الدفعة / رقم الصهرة', 'Parti / döküm numarası'), w('شناسه ردیابی تولید / منشأ ماده؛ در حوزه‌ها یکسان استفاده شود.', 'Production trace / material origin ID; reuse consistently across areas.', 'معرّف تتبّع الإنتاج ومصدر المادة؛ استخدمه موحّداً في المجالات.', 'Üretim izleme / malzeme kaynak kimliği; alanlarda tutarlı kullanın.')],
  [w('NCR', 'NCR', 'NCR', 'NCR'), w('پرونده عدم انطباق با مهار، علت، مسئول و مهلت.', 'Nonconformity case with containment, cause, owner and deadline.', 'ملف عدم المطابقة بالاحتواء والسبب والمسؤول والمهلة.', 'Kontrol altına alma, neden, sorumlu ve tarihli uygunsuzluk dosyası.')],
  [w('عدم قطعیت', 'Measurement uncertainty', 'عدم يقين القياس', 'Ölçüm belirsizliği'), w('بازه مرتبط با نتیجه اندازه‌گیری؛ با تلرانس اشتباه نشود.', 'Interval associated with a measurement; distinct from tolerance.', 'مدى مرتبط بنتيجة القياس؛ مختلف عن التفاوت المسموح.', 'Ölçüm sonucuyla ilişkili aralık; toleransla karıştırmayın.')],
  [w('خط مبنا', 'Baseline', 'خط الأساس', 'Referans'), w('مرجع مقایسه هم‌شرایط پیش از اقدام.', 'Comparable pre-action reference conditions.', 'مرجع في ظروف متقاربة قبل الإجراء.', 'Eylem öncesi eşdeğer karşılaştırma koşulu.')],
  [w('TP / FN / FP / TN', 'TP / FN / FP / TN', 'TP / FN / FP / TN', 'TP / FN / FP / TN'), w('عیب درست / عیب ازدست‌رفته / رد سالم / سالم درست؛ عیب کلاس مثبت است.', 'Correct defect / missed defect / false reject / correct good; defects are positive.', 'عيب صحيح / عيب فائت / رفض سليم / سليم صحيح؛ العيب هو الموجب.', 'Doğru kusur / kaçan kusur / yanlış ret / doğru sağlam; kusur pozitif sınıftır.')],
  [w('مشاهده موازی', 'Shadow mode', 'المراقبة الموازية', 'Paralel gözlem'), w('ارزیابی خروجی مدل کنار تصمیم انسانی، بدون فرمان خط.', 'Evaluate model output alongside human decisions without line commands.', 'تقييم النموذج بجانب القرار البشري بلا أمر للخط.', 'Modeli insan kararı yanında hat komutu vermeden değerlendirme.')],
] as const;
const labels = {
  title: w('راهنمای عملیات کارخانه', 'Factory operations manual', 'دليل عمليات المصنع', 'Fabrika operasyon kılavuzu'),
  intro: w('روش کار، معیار تصمیم و شواهد هر حوزه؛ از داده معتبر تا اقدام مسئولانه.', 'Workflows, decision criteria and evidence for each area: from reliable data to accountable action.', 'طرق العمل ومعايير القرار وأدلة كل مجال؛ من البيانات الموثوقة إلى الإجراء المسؤول.', 'Her alanın akışı, karar ölçütü ve kanıtı; güvenilir veriden sorumlu eyleme.'),
  search: w('جست‌وجوی راهنما', 'Search the manual', 'البحث في الدليل', 'Kılavuzda ara'),
  placeholder: w('نقش، حوزه، OEE، کالیبراسیون…', 'Role, area, OEE, calibration…', 'دور، مجال، OEE، معايرة…', 'Rol, alan, OEE, kalibrasyon…'),
  contents: w('فصل‌های راهنما', 'Manual chapters', 'فصول الدليل', 'Kılavuz bölümleri'),
  purpose: w('کاربرد در کارخانه', 'Factory use', 'الاستخدام في المصنع', 'Fabrikada kullanım'),
  steps: w('مراحل اجرا', 'Operating steps', 'خطوات التنفيذ', 'Uygulama adımları'),
  method: w('روش و شاخص', 'Method and metric', 'الطريقة والمؤشر', 'Yöntem ve gösterge'),
  decision: w('معیار تصمیم و حدود روش', 'Decision criteria and method limits', 'معايير القرار وحدود الطريقة', 'Karar ölçütü ve yöntem sınırları'),
  evidence: w('خروجی و شواهد لازم', 'Outputs and required evidence', 'المخرجات والأدلة المطلوبة', 'Çıktılar ve gerekli kanıt'),
  next: w('رفتن به محیط کار', 'Go to the work area', 'الانتقال للعمل', 'Çalışma alanına git'),
  roles: w('مسیر کاری نقش‌ها', 'Role workflows', 'مسارات الأدوار', 'Rol iş akışları'),
  yours: w('نقش شما', 'Your role', 'دورك', 'Rolünüz'),
  tools: w('انتخاب ابزار بر اساس پرسش', 'Choose a tool for your question', 'اختر الأداة حسب السؤال', 'Sorunuza göre araç seçin'),
  tool: w('ابزار', 'Tool', 'الأداة', 'Araç'),
  application: w('ورودی ← نتیجه و کاربرد', 'Input → result and use', 'المدخل ← النتيجة والاستخدام', 'Girdi → sonuç ve kullanım'),
  glossary: w('واژه‌نامه عملیاتی', 'Operational glossary', 'المصطلحات التشغيلية', 'Operasyon terimleri'),
  empty: w('فصلی پیدا نشد. عبارت کوتاه‌تر یا نام حوزه را امتحان کنید.', 'No chapter matches. Try a shorter phrase or area name.', 'لا يوجد فصل مطابق. جرّب عبارة أقصر أو اسم مجال.', 'Eşleşen bölüm yok. Kısa ifade veya alan adı deneyin.'),
  clear: w('پاک‌کردن جست‌وجو', 'Clear search', 'مسح البحث', 'Aramayı temizle'),
  results: w('فصل یافت شد', 'chapters found', 'فصول موجودة', 'bölüm bulundu'),
  sources: w('مراجع روش‌ها', 'Method references', 'مراجع الطرق', 'Yöntem kaynakları'),
  permission: w('اقدامات مطابق دسترسی حساب شما نمایش داده می‌شوند؛ مجوز نهایی در سرور کنترل می‌شود.', 'Actions follow your account access; the server enforces final permission.', 'تظهر الإجراءات حسب صلاحيات حسابك ويفرض الخادم الصلاحية النهائية.', 'İşlemler hesap erişiminize göre gösterilir; son izni sunucu uygular.'),
};
const references = [
  {url: 'https://www.itl.nist.gov/div898/handbook/pmc/section1/pmc16.htm', title: w('NIST — قابلیت فرآیند', 'NIST — Process capability', 'NIST — قابلية العملية', 'NIST — Süreç yeterliliği')},
  {url: 'https://archive.ics.uci.edu/dataset/198/steel%2Bplates%2Bfaults', title: w('UCI — مجموعه عیوب ورق فولادی', 'UCI — Steel Plates Faults dataset', 'UCI — بيانات عيوب الصفائح', 'UCI — Çelik levha kusur verisi')},
  {url: 'https://csrc.nist.gov/pubs/sp/800/82/r3/final', title: w('NIST SP 800-82r3 — امنیت صنعتی', 'NIST SP 800-82r3 — OT security', 'NIST SP 800-82r3 — أمن الصناعة', 'NIST SP 800-82r3 — OT güvenliği')},
];
const normalize = (text: string) => text.toLocaleLowerCase().replace(/[\u064b-\u065f\u0670]/g, '').replace(/ي/g, 'ی').replace(/ك/g, 'ک').replace(/\s+/g, ' ').trim();
export type OperationManualProps = {userRole?: string; onOpen?: (key: string) => void; canOpen?: (key: string) => boolean};
export function OperationManual({userRole, onOpen, canOpen}: OperationManualProps = {}) {
  const {locale} = useLocale();
  const [query, setQuery] = useState('');
  const [selected, setSelected] = useState('start');
  const index = ({fa: 0, en: 1, ar: 2, tr: 3} as Record<Language, number>)[locale];
  const text = (value: Words) => value[index];
  const needle = normalize(query);
  const filtered = articles.filter(item => {
    const extra = item.id === 'start' ? roles.flatMap(role => [text(role.name), text(role.task)]) : item.id === 'laboratory' ? [...tools.flatMap(tool => [text(tool[1]), text(tool[2])]), ...glossary.flatMap(entry => entry.map(text))] : [];
    return normalize([text(item.title), text(item.summary), text(item.purpose), ...item.steps.map(text), text(item.method), item.formula || '', text(item.decision), text(item.evidence), ...item.actions.map(item => text(item.label)), ...extra].join(' ')).includes(needle);
  });
  const active = filtered.find(item => item.id === selected) || filtered[0];
  const available = (key: string) => Boolean(onOpen) && (canOpen ? canOpen(key) : key.startsWith('lab:') || ['profile', 'settings', 'activity', 'models'].includes(key));
  const allActions = articles.flatMap(item => item.actions);
  const openActions = active?.actions.filter(item => available(item.key)) || [];
  return <section className="manual-shell" aria-label={text(labels.title)}>
    <header className="manual-header"><div><h2>{text(labels.title)}</h2><p>{text(labels.intro)}</p></div><div className="manual-search"><label htmlFor="manual-search">{text(labels.search)}</label><input id="manual-search" type="search" value={query} placeholder={text(labels.placeholder)} onChange={event => setQuery(event.target.value)} /><span className="manual-result-count" aria-live="polite">{new Intl.NumberFormat(locale).format(filtered.length)} {text(labels.results)}</span></div></header>
    <div className="manual-layout">
      <nav className="manual-nav" aria-label={text(labels.contents)}><h3>{text(labels.contents)}</h3>{filtered.map(item => <button type="button" key={item.id} className={active?.id === item.id ? 'manual-nav-item is-active' : 'manual-nav-item'} aria-current={active?.id === item.id ? 'page' : undefined} onClick={() => setSelected(item.id)}><span className="manual-nav-number">{new Intl.NumberFormat(locale).format(articles.indexOf(item) + 1)}</span><span><strong>{text(item.title)}</strong><small>{text(item.summary)}</small></span></button>)}</nav>
      {active ? <article className="manual-article" key={active.id}>
        <header className="manual-article-heading"><span className="manual-eyebrow">{new Intl.NumberFormat(locale).format(articles.indexOf(active) + 1)} / {new Intl.NumberFormat(locale).format(articles.length)}</span><h2>{text(active.title)}</h2><p>{text(active.summary)}</p></header>
        <section className="manual-section"><h3>{text(labels.purpose)}</h3><p>{text(active.purpose)}</p></section>
        {active.id === 'start' && <section className="manual-section"><h3>{text(labels.roles)}</h3><div className="manual-role-grid">{roles.map(role => <article className={role.id === userRole ? 'manual-role is-own-role' : 'manual-role'} key={role.id}><h4>{text(role.name)} {role.id === userRole && <span className="manual-role-badge">{text(labels.yours)}</span>}</h4><p>{text(role.task)}</p><div className="manual-inline-actions">{role.keys.filter(available).map(key => <button type="button" key={key} onClick={() => onOpen?.(key)}>{text(allActions.find(item => item.key === key)?.label || labels.next)}</button>)}</div></article>)}</div></section>}
        <section className="manual-section"><h3>{text(labels.steps)}</h3><ol className="manual-steps">{active.steps.map((step, i) => <li key={i}><span className="manual-step-number" aria-hidden="true">{new Intl.NumberFormat(locale).format(i + 1)}</span><p>{text(step)}</p></li>)}</ol></section>
        <section className="manual-section manual-method"><h3>{text(labels.method)}</h3>{active.formula && <div className="manual-formula" dir="ltr"><code>{active.formula}</code></div>}<p>{text(active.method)}</p></section>
        <section className="manual-section manual-decision"><h3>{text(labels.decision)}</h3><p>{text(active.decision)}</p></section>
        {active.id === 'laboratory' && <><section className="manual-section"><h3>{text(labels.tools)}</h3><div className="manual-table-wrap"><table className="manual-tools-table"><thead><tr><th scope="col">{text(labels.tool)}</th><th scope="col">{text(labels.application)}</th></tr></thead><tbody>{tools.map(([key, name, use]) => <tr key={key}><th scope="row">{available(`lab:${key}`) ? <button type="button" onClick={() => onOpen?.(`lab:${key}`)}>{text(name)}</button> : text(name)}</th><td>{text(use)}</td></tr>)}</tbody></table></div></section><section className="manual-section"><h3>{text(labels.glossary)}</h3><dl className="manual-glossary">{glossary.map(([name, meaning]) => <div key={name[0]}><dt>{text(name)}</dt><dd>{text(meaning)}</dd></div>)}</dl></section></>}
        <section className="manual-section manual-evidence"><h3>{text(labels.evidence)}</h3><p>{text(active.evidence)}</p></section>
        {openActions.length > 0 && <footer className="manual-actions"><h3>{text(labels.next)}</h3><div>{openActions.map(item => <button type="button" key={item.key} onClick={() => onOpen?.(item.key)}>{text(item.label)}</button>)}</div><p>{text(labels.permission)}</p></footer>}
        {['quality', 'model', 'governance'].includes(active.id) && <aside className="manual-references"><h3>{text(labels.sources)}</h3>{references.filter((_, i) => active.id === 'quality' ? i === 0 : active.id === 'model' ? i === 1 : i === 2).map(ref => <a href={ref.url} key={ref.url} target="_blank" rel="noreferrer">{text(ref.title)}</a>)}</aside>}
      </article> : <div className="manual-empty" role="status"><p>{text(labels.empty)}</p><button type="button" onClick={() => setQuery('')}>{text(labels.clear)}</button></div>}
    </div>
  </section>;
}
