import type {RecordRow} from './api';
const num=(r:RecordRow,key:string)=>typeof r.data[key]==='number'?Number(r.data[key]):0;
export function recordTitle(r:RecordRow){return [r.data.batch||r.data.code||r.data.meter||r.data.instrument||r.data.part||r.data.asset,r.data.title||r.data.name||r.data.line||r.data.dimension||r.data.revision].filter(Boolean).join(' · ');}
export function recordDay(r:RecordRow){return String(r.data.date||r.created_at.slice(0,10));}
export function periodRows(records:RecordRow[],days:number,today:string){if(!days)return records;const end=Date.parse(today+'T00:00:00Z'),start=end-(days-1)*86400000;return records.filter(r=>{const n=Date.parse(recordDay(r)+'T00:00:00Z');return n>=start&&n<=end;});}
export function productionMetrics(records:RecordRow[]){const rows=records.filter(r=>r.kind==='production'&&r.status==='approved');const sum=(key:string)=>rows.reduce((n,r)=>n+num(r,key),0);const planned=sum('plannedMinutes'),run=sum('runMinutes'),total=sum('total'),good=sum('good'),ideal=rows.reduce((n,r)=>n+num(r,'idealCycleSeconds')*num(r,'total')/60,0);const availability=planned?run/planned:null,performance=run?ideal/run:null,quality=total?good/total:null;return{shifts:rows.length,total,good,scrap:total-good,downtime:planned-run,availability,performance,quality,oee:availability!==null&&performance!==null&&quality!==null?availability*performance*quality:null};}
export function inspectionMetrics(records:RecordRow[]){const rows=records.filter(r=>r.kind==='inspection'&&r.status==='approved'),samples=rows.reduce((s,r)=>s+num(r,'sampleCount'),0),defects=rows.reduce((s,r)=>s+num(r,'defects'),0);return{batches:rows.length,samples,defects,defectRate:samples?defects/samples:null,outside:rows.filter(r=>Math.abs(num(r,'measured')-num(r,'nominal'))>num(r,'tolerance')).length};}
export function energyMetrics(records:RecordRow[],carrier:string){const rows=records.filter(r=>r.kind==='energy'&&r.status==='approved'&&r.data.carrier===carrier);const consumption=rows.reduce((s,r)=>s+num(r,'readingEnd')-num(r,'readingStart'),0),tonnage=rows.reduce((s,r)=>s+num(r,'tonnage'),0);return{count:rows.length,consumption:rows.length?consumption:null,tonnage,intensity:tonnage?consumption/tonnage:null,outage:rows.reduce((s,r)=>s+num(r,'outageMinutes'),0)};}
export type OperationalAlert={record:RecordRow;reason:'maintenance_due'|'critical_maintenance'|'calibration_expired'|'service_due'|'low_stock'|'ncr_due'|'dimension_outside';severity:'critical'|'warning'};
export function operationalAlerts(records:RecordRow[],today:string):OperationalAlert[]{const alerts:OperationalAlert[]=[];for(const r of records){if(r.status==='rejected')continue;const d=r.data;if(r.kind==='maintenance'&&!d.resolution){if(d.priority==='بحرانی')alerts.push({record:r,reason:'critical_maintenance',severity:'critical'});else if(String(d.due)<today)alerts.push({record:r,reason:'maintenance_due',severity:'warning'});}if(r.status!=='approved')continue;if(r.kind==='calibration'&&String(d.expiresAt)<today)alerts.push({record:r,reason:'calibration_expired',severity:'critical'});if(r.kind==='asset'&&new Date(Date.parse(String(d.lastService)+'T00:00:00Z')+num(r,'serviceIntervalDays')*86400000).toISOString().slice(0,10)<today)alerts.push({record:r,reason:'service_due',severity:'warning'});if(r.kind==='inventory'&&num(r,'quantity')<num(r,'minimum'))alerts.push({record:r,reason:'low_stock',severity:'warning'});if(r.kind==='ncr'&&String(d.due)<today&&!d.action)alerts.push({record:r,reason:'ncr_due',severity:'critical'});if(r.kind==='inspection'&&Math.abs(num(r,'measured')-num(r,'nominal'))>num(r,'tolerance'))alerts.push({record:r,reason:'dimension_outside',severity:'critical'});}return alerts.sort((a,b)=>Number(b.severity==='critical')-Number(a.severity==='critical'));}
export function relatedRecords(row:RecordRow,records:RecordRow[]){const groups=[['batch','lot'],['part','product'],['instrument'],['asset']];return records.filter(r=>r.id!==row.id&&groups.some(keys=>{const values=keys.map(k=>String(row.data[k]||'').trim()).filter(Boolean);if(row.kind==='asset'&&keys[0]==='asset'&&row.data.code)values.push(String(row.data.code).trim());const other=keys.map(k=>String(r.data[k]||'').trim()).filter(Boolean);if(r.kind==='asset'&&keys[0]==='asset'&&r.data.code)other.push(String(r.data.code).trim());return values.some(value=>other.includes(value));}));}
export const domainColumns:Record<string,string[]>={production:['batch','line','date','total','good'],inspection:['batch','part','measured','defects','instrument'],maintenance:['asset','title','priority','due','resolution'],energy:['meter','carrier','date','tonnage'],asset:['code','name','criticality','lastService'],recipe:['part','revision','material','wireDiameter'],calibration:['instrument','name','expiresAt','certificate'],ncr:['batch','title','severity','owner','due'],inventory:['code','name','quantity','minimum','unit']};
