import {useEffect,useState} from 'react';
import {UserRound,Save,Activity,Settings,ShieldCheck,Server,RefreshCw} from 'lucide-react';
import {api,faDate,faNumber,type User,type Catalog} from './api';

export type Preferences={density:'comfortable'|'compact';startPage:string;notifications:boolean};
type Profile={user:User;department:string;jobTitle:string;email:string;phone:string;preferences:Preferences};
export const eventLabels:Record<string,string>={'auth.login':'ورود به سامانه','auth.logout':'خروج از سامانه','auth.failed':'تلاش ورود ناموفق','auth.password':'تغییر رمز','record.created':'ثبت رکورد','record.updated':'تغییر یا بررسی رکورد','user.created':'ایجاد حساب','user.updated':'تغییر دسترسی حساب','profile.updated':'ویرایش پروفایل و تنظیمات','demo.record.seeded':'آماده‌سازی نمونه آموزشی'};
export function EventTable({events}:{events:any[]}){return events.length?<div className="table-scroll"><table><thead><tr><th>زمان</th><th>عامل</th><th>فعالیت</th><th>جزئیات</th></tr></thead><tbody>{events.map(a=><tr key={a.id}><td>{faDate(a.created_at)}</td><td>{a.actor_name||'سامانه'}</td><td>{eventLabels[a.action]||a.action}</td><td><details><summary>نمایش مرجع</summary><code dir="ltr">{a.target||'—'}</code><pre dir="ltr">{a.details}</pre></details></td></tr>)}</tbody></table></div>:<div className="empty-state"><Activity/><h3>هنوز فعالیتی ثبت نشده است</h3><p>رویدادهای حساب شما پس از انجام عملیات در اینجا ثبت می‌شوند.</p></div>;}
export function PersonalWorkspace({page,user,catalog,onUpdate}:{page:string;user:User;catalog:Catalog[];onUpdate:(user:User,preferences:Preferences)=>void}){
 const[profile,setProfile]=useState<Profile|null>(null),[events,setEvents]=useState<any[]>([]),[error,setError]=useState(''),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{setError('');setSaved(false);if(page==='activity')api<any>('/activity').then(r=>setEvents(r.events)).catch(e=>setError(e.message));else api<Profile>('/profile').then(setProfile).catch(e=>setError(e.message));},[page,user.id]);
 async function save(e:React.FormEvent){e.preventDefault();if(!profile)return;setBusy(true);setError('');setSaved(false);try{const next=await api<Profile>('/profile','PATCH',{...profile,name:profile.user.name});setProfile(next);onUpdate(next.user,next.preferences);setSaved(true);}catch(e){setError(e instanceof Error?e.message:'ذخیره انجام نشد');}finally{setBusy(false);}}
 const field=(key:'department'|'jobTitle'|'email'|'phone',label:string,type='text')=>profile&&<label>{label}<input type={type} maxLength={key==='phone'?30:key==='email'?120:100} value={profile[key]} onChange={e=>setProfile({...profile,[key]:e.target.value})}/></label>;
 return <section className="panel personal-panel">{error&&<div className="notice error" role="alert">{error}</div>}{saved&&<div className="notice success" role="status">اطلاعات شخصی شما ذخیره شد.</div>}{page==='activity'?<><div className="panel-title"><h2>فعالیت‌های حساب من</h2><Activity size={20}/></div><p className="section-caption">۲۰۰ رویداد آخر حساب شما؛ سوابق سایر کاربران در این بخش نمایش داده نمی‌شوند.</p><EventTable events={events}/></>:profile?<><div className="profile-summary"><div className="profile-avatar"><UserRound size={33}/></div><div><h2>{profile.user.name}</h2><p>{profile.user.roleLabel} · <span dir="ltr">{profile.user.username}</span></p><span className="badge approved">حساب سازمانی فعال</span></div><ShieldCheck size={28}/></div><form onSubmit={save} className="record-modal inline-form">{page==='profile'?<><h3>اطلاعات فردی و سازمانی</h3><div className="form-grid"><label>نام و نام خانوادگی<input required minLength={2} maxLength={100} value={profile.user.name} onChange={e=>setProfile({...profile,user:{...profile.user,name:e.target.value}})}/></label>{field('jobTitle','عنوان شغلی')}{field('department','واحد سازمانی')}{field('email','ایمیل','email')}{field('phone','شماره تماس','tel')}<label>نقش و سطح دسترسی<input value={profile.user.roleLabel} disabled/><small>تغییر نقش فقط توسط مدیر سامانه انجام می‌شود.</small></label></div></>:<><h3><Settings size={18}/> تنظیمات فضای کاری من</h3><div className="form-grid"><label>تراکم نمایش<select value={profile.preferences.density} onChange={e=>setProfile({...profile,preferences:{...profile.preferences,density:e.target.value as Preferences['density']}})}><option value="comfortable">خوانا و استاندارد</option><option value="compact">فشرده برای نمایشگر عملیات</option></select></label><label>صفحه شروع پس از ورود<select value={profile.preferences.startPage} onChange={e=>setProfile({...profile,preferences:{...profile.preferences,startPage:e.target.value}})}><option value="overview">نمای کلی</option>{catalog.map(c=><option key={c.kind} value={c.kind}>{c.title}</option>)}</select></label><label>پیام تأیید عملیات<select value={String(profile.preferences.notifications)} onChange={e=>setProfile({...profile,preferences:{...profile.preferences,notifications:e.target.value==='true'}})}><option value="true">نمایش پیام موفقیت</option><option value="false">بدون پیام موفقیت</option></select><small>خطاها و پیام‌های امنیتی همیشه نمایش داده می‌شوند.</small></label><label>زبان و منطقه زمانی<input disabled value="فارسی · تهران"/></label></div><div className="notice subtle">تنظیمات به حساب شما وابسته است و برای کاربران دیگر تغییر نمی‌کند.</div></>}<div className="form-actions"><button className="primary" disabled={busy}><Save size={17}/>{busy?'در حال ذخیره…':'ذخیره تغییرات'}</button></div></form></>:<p className="section-caption">در حال دریافت پروفایل…</p>}</section>;
}
export function SystemMonitor(){
 const[data,setData]=useState<any>(null),[error,setError]=useState('');
 const load=()=>api<any>('/system').then(setData).catch(e=>setError(e.message));useEffect(()=>{load();},[]);
 return <>{error&&<div className="notice error">{error}</div>}<section className="panel"><div className="panel-title"><h2><Server size={20}/> مانیتورینگ اختصاصی پلتفرم</h2><button className="secondary" onClick={load}><RefreshCw size={16}/> دریافت وضعیت</button></div>{data?<><div className="metric-grid">{[['کاربران فعال',data.counts.activeUsers],['نشست‌های معتبر',data.counts.sessions],['رکوردهای سامانه',data.counts.records],['رویدادهای ثبت‌شده',data.counts.audit]].map(([title,value])=><article className="metric-card" key={title}><span>{title}</span><strong>{faNumber(value)}</strong></article>)}</div><div className="system-facts"><span>دیتابیس <b>{data.database==='ok'?'سالم':data.database}</b></span><span>حافظه فرآیند <b>{faNumber(data.memoryMb)} MB</b></span><span>زمان فعالیت <b>{faNumber(data.uptimeSeconds)} ثانیه</b></span><span>اتصال API <b>{data.transport}</b></span><span>نسخه <code>{data.sha.slice(0,12)}</code></span></div><p className="section-caption">وضعیت فرآیند پلتفرم و ۱۰۰ درخواست اخیر همین فضای کاری. لاگ خام میزبان و سرویس‌های سایر پروژه‌ها از وب ارائه نمی‌شود.</p><div className="table-scroll"><table><thead><tr><th>زمان</th><th>متد</th><th>مسیر</th><th>پاسخ</th><th>زمان پاسخ</th></tr></thead><tbody>{data.requests.map((r:any,i:number)=><tr key={i}><td>{faDate(r.at)}</td><td dir="ltr">{r.method}</td><td dir="ltr" className="mono">{r.path}</td><td><span className={`badge ${r.status>=400?'rejected':'approved'}`}>{r.status}</span></td><td>{faNumber(r.durationMs)} ms</td></tr>)}</tbody></table></div></>:<p>در حال دریافت وضعیت…</p>}</section></>;
}
