import {useEffect,useState} from 'react';
import {Download,Search,ChevronLeft,ChevronRight,RefreshCw} from 'lucide-react';
import {api,ApiError,faNumber,faDate,faDateTime,exportCsv,statusLabels,type Workspace,type RecordRow} from './api';
import {useLocale,translate as t} from './i18n';
import {w} from './copy';
import {JalaliDateInput} from './JalaliDateInput';
type Result={records:RecordRow[];total:number;page:number;pageSize:number;pages:number};
type Summary={summary:{shifts:number;total:number;good:number;scrap:number;downtime:number;oee:number|null};days:{date:string;shifts:number;good:number;scrap:number;oee:number|null}[];daysLimited:boolean;dayCount:number};
export function ReportingWorkspace({workspace,onOpen,onSessionExpired}:{workspace:Workspace;onOpen:(row:RecordRow)=>void;onSessionExpired:()=>void}){
 useLocale();const[kind,setKind]=useState(workspace.catalog[0]?.kind||'production'),[status,setStatus]=useState(''),[query,setQuery]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(1),[requestKey,setRequestKey]=useState(0),[result,setResult]=useState<Result|null>(null),[summary,setSummary]=useState<Summary|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const[criteria,setCriteria]=useState({kind:workspace.catalog[0]?.kind||'production',status:'',query:'',from:'',to:''});
 const catalog=workspace.catalog.find(c=>c.kind===criteria.kind);
 useEffect(()=>{let active=true;setBusy(true);setError('');setResult(null);setSummary(null);const params=new URLSearchParams({kind:criteria.kind,status:criteria.status,q:criteria.query,from:criteria.from,to:criteria.to,page:String(page),pageSize:'25'});Promise.all([api<Result>('/records/search?'+params),api<Summary>('/reports/production?'+new URLSearchParams({from:criteria.from,to:criteria.to}))]).then(([rows,next])=>{if(active){setResult(rows);setSummary(next);}}).catch(e=>{if(active){setError(e.message);if(e instanceof ApiError&&e.status===401)onSessionExpired();}}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[requestKey,page,criteria]);
 const apply=(e:React.FormEvent)=>{e.preventDefault();setPage(1);setCriteria({kind,status,query,from,to});};
 return <div className="report-workspace"><section className="ops-panel"><div className="ops-panel-title"><div><span className="section-kicker">{w('گزارش قابل اتکا','VERIFIABLE REPORTING','تقارير قابلة للتحقق','DOĞRULANABİLİR RAPORLAMA')}</span><h2>{w('سوابق و عملکرد کارخانه','Factory records and performance','سجلات وأداء المصنع','Fabrika kayıtları ve performansı')}</h2></div><button className="secondary" disabled={busy} onClick={()=>setRequestKey(k=>k+1)}><RefreshCw size={16}/>{t('به‌روزرسانی')}</button></div><p className="panel-explainer">{w('جستجو روی تمام سوابق مجاز اجرا می‌شود. شاخص‌های تولید از کل شیفت‌های تأییدشده در بازه انتخابی محاسبه می‌شوند و به صفحه جدول وابسته نیستند.','Search covers all authorised records. Production indicators use every approved shift in the selected period, independently of table pagination.','يشمل البحث جميع السجلات المسموح بها. تستخدم مؤشرات الإنتاج كل الورديات المعتمدة في الفترة المختارة بغض النظر عن صفحة الجدول.','Arama tüm yetkili kayıtları kapsar. Üretim göstergeleri tablo sayfasından bağımsız olarak seçilen dönemdeki tüm onaylı vardiyaları kullanır.')}</p><form className="form-grid report-filters" onSubmit={apply}><label>{w('حوزه ثبت','Record domain','مجال السجل','Kayıt alanı')}<select value={kind} onChange={e=>setKind(e.target.value)}>{workspace.catalog.map(c=><option key={c.kind} value={c.kind}>{t(c.title)}</option>)}</select></label><label>{t('وضعیت')}<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">{w('همه وضعیت‌ها','All statuses','جميع الحالات','Tüm durumlar')}</option>{Object.entries(statusLabels).map(([code,label])=><option key={code} value={code}>{t(label)}</option>)}</select></label><label>{w('عبارت یا شناسه پرونده','Text or record ID','النص أو معرف السجل','Metin veya kayıt kimliği')}<input maxLength={120} value={query} onChange={e=>setQuery(e.target.value)}/></label><label>{w('از تاریخ','From date','من تاريخ','Başlangıç tarihi')}<JalaliDateInput value={from} onChange={setFrom} disabled={busy} required={false}/></label><label>{w('تا تاریخ','To date','إلى تاريخ','Bitiş tarihi')}<JalaliDateInput value={to} onChange={setTo} disabled={busy} required={false}/></label><div className="report-submit"><button className="primary" disabled={busy}><Search size={16}/>{w('اعمال فیلتر','Apply filters','تطبيق التصفية','Filtreleri uygula')}</button></div></form>{error&&<div className="notice error" role="alert">{t(error)}</div>}</section>
 {summary&&<><div className="ops-metrics">{[[w('شیفت تأییدشده','Approved shifts','ورديات معتمدة','Onaylı vardiyalar'),faNumber(summary.summary.shifts)],[w('تولید سالم','Good output','الإنتاج السليم','Sağlam üretim'),faNumber(summary.summary.good)],[w('ضایعات ثبت‌شده','Recorded scrap','الهدر المسجل','Kayıtlı fire'),faNumber(summary.summary.scrap)],[w('اثربخشی وزنی تجهیزات','Weighted equipment effectiveness','فعالية المعدات المرجحة','Ağırlıklı ekipman etkinliği'),summary.summary.oee===null?'—':faNumber(summary.summary.oee*100,1)+'%']].map(([label,value])=><article className="ops-metric" key={label}><span>{label}</span><strong>{value}</strong><small>{w('کل بازه انتخابی · تأییدشده','Entire selected period · approved','كامل الفترة المختارة · معتمد','Seçilen dönemin tamamı · onaylı')}</small></article>)}</div><section className="ops-panel"><h2>{w('روند روزانه تولید تأییدشده','Daily approved production','الإنتاج اليومي المعتمد','Günlük onaylı üretim')}</h2>{summary.daysLimited&&<p className="notice amber">{w('جدول روند ۳۶۶ روز آخر را نمایش می‌دهد؛ جمع شاخص‌ها شامل کل بازه است.','The trend table shows the latest 366 days; indicator totals cover the entire period.','يعرض جدول الاتجاه آخر ٣٦٦ يوماً؛ إجماليات المؤشرات تشمل كامل الفترة.','Eğilim tablosu son 366 günü gösterir; gösterge toplamları tüm dönemi kapsar.')}</p>}<div className="table-scroll"><table><thead><tr><th>{t('تاریخ')}</th><th>{w('شیفت','Shifts','الورديات','Vardiyalar')}</th><th>{w('سالم','Good','سليم','Sağlam')}</th><th>{w('ضایعات','Scrap','هدر','Fire')}</th><th>OEE</th></tr></thead><tbody>{summary.days.map(day=><tr key={day.date}><td>{faDate(day.date)}</td><td>{faNumber(day.shifts)}</td><td>{faNumber(day.good)}</td><td>{faNumber(day.scrap)}</td><td>{day.oee===null?'—':faNumber(day.oee*100,1)+'%'}</td></tr>)}</tbody></table></div>{!summary.days.length&&<p className="empty-inline">{w('در این بازه شیفت تأییدشده‌ای ثبت نشده است.','No approved shift is recorded in this period.','لا توجد وردية معتمدة مسجلة في هذه الفترة.','Bu dönemde onaylı vardiya kaydı yok.')}</p>}</section></>}
 <section className="ops-panel"><div className="ops-panel-title"><h2>{catalog?t(catalog.title):''}</h2><button className="secondary" disabled={busy||!result?.records.length||!catalog} onClick={()=>result&&catalog&&exportCsv(result.records,catalog)}><Download size={16}/>{w('CSV همین صفحه','CSV of this page','CSV لهذه الصفحة','Bu sayfanın CSV dosyası')}</button></div>{busy?<p role="status">{w('در حال دریافت گزارش…','Loading report…','جارٍ تحميل التقرير…','Rapor yükleniyor…')}</p>:result&&<><p className="section-caption">{w('تعداد کل مطابق فیلتر','Total matching records','إجمالي السجلات المطابقة','Eşleşen toplam kayıt')}: {faNumber(result.total)}</p><div className="table-scroll"><table><thead><tr><th>{t('شناسه')}</th><th>{t('وضعیت')}</th><th>{t('ثبت‌کننده')}</th><th>{w('آخرین تغییر','Last updated','آخر تحديث','Son güncelleme')}</th><th>{w('پرونده','Record','السجل','Kayıt')}</th></tr></thead><tbody>{result.records.map(row=><tr key={row.id}><td><strong>{String(row.data.batch||row.data.code||row.data.title||row.data.material||row.data.instrument||row.data.meter||row.id.slice(0,8))}</strong><small className="temporary-label" dir="ltr">{row.id.slice(0,8)}</small></td><td><span className={'badge '+row.status}>{t(statusLabels[row.status])}</span></td><td>{row.creator_name}</td><td>{faDateTime(row.updated_at)}</td><td><button className="record-open" onClick={()=>onOpen(row)}>{w('باز کردن','Open','فتح','Aç')}</button></td></tr>)}</tbody></table></div>{!result.records.length&&<p className="empty-inline">{w('سوابقی مطابق فیلتر نیست.','No records match the filters.','لا توجد سجلات مطابقة للتصفية.','Filtrelerle eşleşen kayıt yok.')}</p>}<div className="table-toolbar"><span>{w('صفحه','Page','الصفحة','Sayfa')} {faNumber(result.page)} / {faNumber(Math.max(1,result.pages))}</span><div><button className="secondary" disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronRight size={16}/>{w('قبلی','Previous','السابق','Önceki')}</button><button className="secondary" disabled={page>=result.pages} onClick={()=>setPage(p=>p+1)}>{w('بعدی','Next','التالي','Sonraki')}<ChevronLeft size={16}/></button></div></div></>}</section></div>;
}
