import {translate as t, useLocale, LanguageSelector} from './i18n';
import {ArrowLeft,ClipboardList,Clock,ShieldCheck} from 'lucide-react';
import {faNumber,statusLabels,type User,type Workspace} from './api';
export function RolePriorities({user,workspace,onOpen}:{user:User;workspace:Workspace;onOpen:(kind:string)=>void}){
 const own=workspace.records.filter(r=>r.creator===user.id),drafts=own.filter(r=>r.status==='draft'),submitted=own.filter(r=>r.status==='submitted'),reviews=workspace.records.filter(r=>r.status==='submitted'&&r.creator!==user.id&&workspace.catalog.some(c=>c.kind===r.kind&&c.approve));
 const focus:Record<string,string[]>={admin:['production','inspection','maintenance','energy'],executive:['production','ncr','maintenance','energy'],production:['production','inventory','ncr'],quality:['inspection','calibration','ncr'],maintenance:['maintenance','asset','inventory'],energy:['energy'],engineering:['recipe','asset'],auditor:['production','inspection','ncr']};
 const queue=[...reviews,...drafts].slice(0,5);
 return <section className="panel role-priorities"><div className="panel-title"><h2>{t("میز کار")} {t(user.roleLabel)}</h2><span>{t("وظایف و فعالیت‌های مرتبط با حساب شما")}</span></div><div className="personal-stat-grid">{[[ClipboardList,t('پیش‌نویس‌های من'),drafts.length],[Clock,t('ارسال‌های من در انتظار بررسی'),submitted.length],[ShieldCheck,t('نیازمند بررسی توسط من'),reviews.length]].map(([Icon,label,n]:any)=><article key={t(label)}><Icon size={21}/><span>{t(label)}</span><b>{faNumber(n)}</b></article>)}</div><div className="role-focus">{(focus[user.role]||[]).filter(kind=>workspace.catalog.some(c=>c.kind===kind)).map(kind=>{const c=workspace.catalog.find(c=>c.kind===kind)!;const rows=workspace.records.filter(r=>r.kind===kind);return <button key={kind} onClick={()=>onOpen(kind)}><strong>{t(c.title)}</strong><span>{faNumber(rows.filter(r=>r.status==='approved').length)} {t('تأییدشده ·')} {faNumber(rows.filter(r=>r.status==='submitted').length)} {t('در بررسی')}</span><ArrowLeft size={16}/></button>;})}</div>{queue.length>0&&<div className="recent-list">{queue.map(r=><button key={r.id} onClick={()=>onOpen(r.kind)}><ClipboardList size={18}/><span><strong>{Object.values(r.data).slice(0,2).join(' · ')}</strong><small>{r.creator===user.id?t('ثبت من'):t('برای بررسی مستقل')} · {t(workspace.catalog.find(c=>c.kind===r.kind)?.title)}</small></span><span className={`badge ${r.status}`}>{t(statusLabels[r.status])}</span></button>)}</div>}</section>;
}
